### PR TITLE
Fixed: Enter on Delete profile confirmation deleting all unused profiles

### PR DESCRIPTION
**Pull request by kiityman1**
#### Issues Fixed or Closed by this PR

* # All quality profiles being deleted when pressing enter on the quality profile deletion screen.

### CODE REVIEW

**Comment by SadFarm1** [comment]
Build failed, try again

**Comment by Qstick** [comment]
Build did not fail, all checks passed. Circle check is rouge.....

**Comment by kiityman1** [comment]
> Build did not fail, all checks passed. Circle check is rouge.....

So my pull request is okay?

**Comment by Qstick** [comment]
> > Build did not fail, all checks passed. Circle check is rouge.....
> 
> So my pull request is okay?

Yes

**Pull request merged**
