### PR TITLE
[wip] Switch quote styling in UI JS files

### PR DESCRIPTION
**Pull request by jamesmacwhite**
#### Database Migration
NO

#### Description

So this more of a code styling thing, but its recommended that string values in JS are quoted with double quotes in most cases. Exceptions I think in this case are when HTML elements are being added and it makes no sense to have to escape parts all the time with `\` because it will get messy.

Currently codacy is reporting a lot of "Code Style" errors for various JS files in this case, this should knock out a fair bit of the "errors". I didn't modify the `JsLibraries` contents, because that's external libraries which can't really be modified.

I did run automated processing on the files to do the replace work, however I have tried to regex ignore areas where I don't want things to be changed i.e. `"' + variables + '"`.

I have ran `npm start` to confirm no errors and inspected the UI to look for regressions.

Totally reject this PR if its not worth it, but codacy will be happy lol, check the report and see the errors "fixed"

Marked WIP currently because the risk of regressing UI areas.

### CODE REVIEW

**Comment by galli-leo** [comment]
Lol. Meanwhile Webstorm is yelling at me for using double quotes. :P

**Comment by jamesmacwhite** [comment]
https://www.codacy.com/app/leonardo.galli/Radarr/pullRequest?prid=856624
image

LOL -5604. Not bad lol.

Probably shouldn't merge this for now thought, because close to release on develop and this has potential regression risk.

**Comment by galli-leo** [comment]
If it's finished I will just merge it. The alt title stuff has a much higher risk of impacting anything 😬. And develop is still a few days out.

**Comment by jamesmacwhite** [comment]
I guess I wanted to try and just test the UI locally more to make sure the automated processing didn't break anything with areas that need specific quote patterns and such. Might be difficult to fully test all that, but what I do know is as the PR stands.

* `npm start` runs without any issues :thumbsup:
* UI loads without any console errors. :thumbsup:

The automated replace was only as good as the human that wrote it lol.

**Pull request closed without merging**
