### PR TITLE
Temporary fix for PTP approved and golden uploads on deluge.

### PR DESCRIPTION
**Pull request by shauder**
The emojis make Deluge error out.

#### Database Migration
YES | NO

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* #https://github.com/Radarr/Radarr/issues/761

### CODE REVIEW

**Comment by galli-leo** [comment]
While that does fix the issue, maybe we could just remove the emojis before downloading the torrent file or adding the file to deluge?

**Comment by shauder** [comment]
I was going to look into how to do that more but my first every look at the code was late last night and I figured this would resolve it temporarily now for a few people.

**Comment by onedr0p** [comment]
I like removing the emojis actually, that seems fine to me. In the long run we need a column for tracker torrent types, like golden, free leech, etc..

**Comment by galli-leo** [comment]
@onedr0p See my latest PR for something like that ;)

**Comment by shauder** [comment]
https://github.com/Radarr/Radarr/pull/1377

That seems to be a better solution so I will close

**Pull request closed without merging**
