### PR TITLE
New: Add Release Type Calendar Filter

### LINKED ISSUE #6482: Filter out release availability types from Calendar views
**Is your feature request related to a problem? Please describe.**
The calendar views may contain a lot of redundant data depending on the Minimum Available settings selected by the user. For instance if a user only wants Released movies, that user still has all Cinema listings taking up significant screen space within the calendar.

**Describe the solution you'd like**
Within the Calendar section of Radarr, I would like to see additional functionality added to the filter options where the user can unselect Cinema, Digital or Physical releases depending on their preference. This would clean up the calendar view of unwanted release types.

### PR DESCRIPTION
**Pull request by FreeRad1cal**
#### Database Migration
NO

#### Description
- Allow multiple selection in the filter menu.
- Add release type filter options to the calendar filter.
- Meets Minimum Availability filter is mutually exclusive with In Cinemas, Physical, and Digital filters. Selecting Meets Minimum Availability unselects the other filters, and vice versa.
- Add Release Type filter to the iCal modal.

#### Screenshot (if UI related)

image
image

#### Todos
- [X] Tests
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #6482

### CODE REVIEW

**Comment by RobinDadswell** [comment]
This doesn't meet the original issues scope as they want to be able to filter on all 3 variants of release type and not just based on the release preference of the movie.

Also we don't allow merge commits, you will need to rebase in the other changes and not include the merge commit.

**Comment by FreeRad1cal** [comment]
> 
> 
> This doesn't meet the original issues scope as they want to be able to filter on all 3 variants of release type and not just based on the release preference of the movie.
> 
> Also we don't allow merge commits, you will need to rebase in the other changes and not include the merge commit.

Unless I misunderstood something, the OP wanted the events in the calendar to reflect the minimum availability setting for a movie. There are four availability types: Announced, In Cinemas, Release, PreDB. There are three calendar event types: Cinemas, Digital, Physical. The Announced, PreDB and Cinemas availability types are met by all three calendar event types. The Released availability type is met only by Digital and Physical calendar event types.

**Comment by bakerboy448** [comment]
> the user can unselect Cinema, Digital or Physical releases depending on their preference

cinema OR digital OR physical is how I read that

**Comment by FreeRad1cal** [comment]
> 
> 
> > the user can unselect Cinema, Digital or Physical releases depending on their preference
> 
> Filtering and hiding/unhiding by cinema OR digital OR physical is how I read that

So just a simple non-persistent filter without regard for the minimum availability? I guess it was the description of the issue that steered me in the direction of using the minimum availability: 
>
>
>The calendar views may contain a lot of redundant data depending on the Minimum Available settings selected by the user. For instance if a user only wants Released movies, that user still has all Cinema listings taking up significant screen space within the calendar.

**Comment by RobinDadswell** [comment]
I like the idea of having the ability to have it filter on release but I think that should be a filter option as well as filters for the individuals so that you can have what you want there as well :)

**Comment by FreeRad1cal** [comment]
@RobinDadswell @bakerboy448 Please take another look.

**Comment by FreeRad1cal** [comment]
@RobinDadswell Rebased my changes to the ASP.NET Core migration. Please take a look. Thanks!

**Comment by bakerboy448** [comment]
Conflicts

**Comment by FreeRad1cal** [comment]
> Conflicts

@bakerboy448 resolved

**Comment by georgeduckett** [comment]
Is there any movement on this issue, I've just come across it as I'm after filtering the iCal feed and this seems to do exactly what I'm after, but it seems like this hasn't had any activity in a while. Is there anything I can to do help?

**Comment by bakerboy448** [comment]
To start OP needs to fix the PR as it is conflicted.

**Comment by georgeduckett** [comment]
Hi @bakerboy448, thanks for the quick response. Sorry if I came across overly terse, or impatient towards the maintainers of this fantastic project. I can see there are more conflicts since they got resolved initially. OP doesn't seem to have much github activity recently though, so wonder if there's any alternative to waiting for them? For example, would it be appropriate for me to submit a more up to date pull request (not sure if I can edit this one, I'd assume not)? Or is there something that can be done with this one?

**Comment by FreeRad1cal** [comment]
Note to project developers: I would love to contribute to this wonderful project that I have used for many years. However, I cannot accept having my time wasted by having my PR go unreviewed and unmerged for months, until a point where I have to spend significant additional time trying to resolve rebase conflicts.

**Pull request closed without merging**
