### PR TITLE
Incorporate Jackett so indexers can be added easier

### PR DESCRIPTION
**Pull request by austinwbest**
#### Database Migration
NO

#### Description
Add a way to save jackett connection information so the indexer list can be fetched from radarr. Eliminates the back and forth with copy/paste over and over to get the URL/API and add them. Once selected on the torznab screen it will prefill the name, url & apikey fields.

Note: There is a 1-2 second delay the first time you load the torznab card for it to fetch the list from jackett (only if the path/api information is provided of course). This is in the API call so kinda is what it is. Trade-off is worth the second/two to avoid the back and forth of adding multiples manually (imo). The drop menu was originally on the main indexer page with the path/api key but the delay when loading the indexer page was uncalled for if you are not adding a jackett indexer so it was moved.

Enhancement, maybe? Since all the Jackett info is available, it is possible to loop through the sites category list and append the **movie** categories to the comma list. Not sure if it is needed though as the default tends to work fine?

Screenshot 2020-10-01 084950

Screenshot 2020-10-01 085057

### CODE REVIEW

**Comment by hotio** [comment]
bogus reply to try and get it on top

**Comment by bakerboy448** [comment]
Fixes #4120

**Comment by hadim** [comment]
I would be really interested in that feature. Is there is still interest in it?

**Comment by hadim** [comment]
@austinwbest would you be interested in making a similar PR to sonarr (https://github.com/Sonarr/Sonarr) ?

**Comment by Qstick** [comment]
Closing due to other plans

**Pull request closed without merging**
