### PR TITLE
Add support multiLanguageTitle in ParsingService.cs

### PR DESCRIPTION
**Pull request by andrey4korop**
**Describe the bug**
**Failed to map movie**  if the torrent has several movie titles in the title (Translated / English) (for example: Енола Голмс / Enola Holmes (2020) UHD WEB-DL 2160p 4K HDR H.265 Ukr/Eng | Sub Ukr/Eng)

#### Database Migration
NO

#### Description
Add support multiLanguageTitle in ParsingService.cs
Add Tests for this problem

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR
Fixes this problem

#### Comment
I don't know C# well and maybe my solution is not perfect, please check and edit my code

### CODE REVIEW

**Comment by Qstick** [comment]
Ideally this should be handled in `Parser.cs` in the `AlternativeTitleRegex`

**Comment by andrey4korop** [comment]
> Ideally this should be handled in `Parser.cs` in the `AlternativeTitleRegex`

maybe like this:
`private static readonly Regex AlternativeTitleRegex = new Regex(@"[ ]+\/[ ]+|[ ]+AKA[ ]+", RegexOptions.IgnoreCase | RegexOptions.Compiled);`  ?

**Comment by odayny** [comment]
Funny enough I faced the same issue recently and my idea was to add a flag to specific indexer(s) in Prowlarr to replace ` / ` before `(yyyy)` with ` .AKA. ` in specific categories.
see #5221. 

In this case we can keep this isolated to specific trackers which really need this. 

If I find some time next week, I'll try it on my setup

**Comment by Qstick** [comment]
> Енола Голмс / Enola Holmes (2020) UHD WEB-DL 2160p 4K HDR H.265 Ukr/Eng | Sub Ukr/Eng)

Yes, then we need some test cases to the `should_parse_movie_alternative_titles` test in ParserFixture

**Pull request closed without merging**
