### PR TITLE
Send all environment variable with Test

### PR DESCRIPTION
**Pull request by lucianor**
Update to send all environment variables with their name into the custom script test. Helpful for debugging and creation of scripts.

#### Database Migration
NO

#### Description
Send all environment variables when clicking on the test button. This will help a lot with scripts creation and debugging. This was a feature request that got closed and never addressed on v2:

https://github.com/Radarr/Radarr/issues/2012

#### Screenshot (if UI related)
Not applicable

#### Todos
Not applicable

### CODE REVIEW

**Comment by bakerboy448** [comment]
Passing all the variables in test with invalid values that don't reflect what would actually be sent doesn't really make sense....

the variables are listed in the docs.
https://wiki.servarr.com/radarr/custom-scripts

**Comment by lucianor** [comment]
> Passing all the variables in test with invalid values that don't reflect what would actually be sent doesn't really make sense....the GitHub issue referenced discussed sending dummy data that would still reflect what was sent for normal notifications. This PR does not do that.
> 

If I change to send dummy values closes to the real ones, would this PR be accepted?

**Comment by austinwbest** [comment]
I dont see the need for this.

If people use the fields to do conditionals it is going to mess things up & require them to recode their stuff. A test is just a test. To see all the fields, they are documented already & this also adds more to keep up with beyond docs if they where to change.

**Comment by lucianor** [comment]
I beg to differ, but not my call.

**Pull request closed without merging**
