### PR TITLE
Bring Diskstation up to date with sonarr.

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Description
See Sonarr/Sonarr#2325 and Sonarr/Sonarr#1764

#### Issues Fixed or Closed by this PR

#2000

### CODE REVIEW

**Comment by alexanderberman** [comment]
This is still an issue. Please implement these fixes.

**Comment by galli-leo** [comment]
You need to fix the merge issues before we can take a look at it. It's why we haven't given any feedback.

**Comment by margaale** [comment]
Sure, no problem, but there were no conflicts when I first submitted this

**Comment by margaale** [comment]
Fixed

**Comment by galli-leo** [comment]
Thanks a ton for the PR, sorry for the confusion about the merge issues, thought they were like this originally.

**Comment by demonbane** [comment]
@margaale Thanks so much for all of your work on this! Looking forward to seeing this in the next update.

**Pull request merged**
