### PR TITLE
Update to .NET 8

### PR DESCRIPTION
**Pull request by Gauvino**
#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.
- Update .NET to 8.0
 - Update .NETFramework to 4.8.1
 - Update packages versions
 - Update MacOS to 12 since earlier version or not supported :
https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md
 - OS-release update to Ubuntu 20.04
 - Fix task: NodeTool@0 to UseNode@1
 - Fix task: reportgenerator@4 to reportgenerator@5

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [X] [Wiki Updates](https://wiki.servarr.com) : https://github.com/Servarr/Wiki/pull/327

### CODE REVIEW

**Comment by bakerboy448** [comment]
- rebase don't merge
- CI failed.

**Comment by Gauvino** [comment]
> FYI You need to start using rebase and stop merging the base branch.

Will use this now no problem sorry

**Comment by Gauvino** [comment]
Everything fixed now waiting for the https://github.com/Servarr/dotnet-linux-x86/pull/5 being merge and other one so we can have .NET 8 build available

**Comment by Gauvino** [comment]
Could I remake another PR the same just with 1 commit ?

**Comment by bakerboy448** [comment]
Or just interactive rebase, drop the merge commit, and force push the branch.

**Comment by Gauvino** [comment]
> Or just interactive rebase, drop the merge commit, and force push the branch.
I don't know how to do that will test.
> 
> Re "fixed" - CI still failing, so not fixed

It is fixed its normal for the CI to fail if there is no release for the dotnet-bsd-crossbuild being added for .NET 8 same for the linux-x64.
https://github.com/Servarr/dotnet-bsd/releases

**Comment by Gauvino** [comment]
> Or just interactive rebase, drop the merge commit, and force push the branch.
> 
> ~Re "fixed" - CI still failing, so not fixed~ Waiting bsd

Please give a video tutorial or anything I don't understand s*** about this really

**Pull request closed without merging**
