### PR TITLE
New: Use websockets to communicate with UI

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description

This PR retargets radarr for .net 4.6.1 which allows us to utilize websockets to communicate between api and UI. This will also require min mono version to be upted to 4.4.2. (The healthcheck has been updated in this PR). Longpolling is still used as a backup if websockets are not supported by browser.

- Retarget projects to .net 4.6.1
- Pull Platform Identification Improvements from Sonarr
- Remove built in SignalR in lieu of NuGet packages.
- Update SignalR to 2.4.0
- Update Owin to 3.1.0
- Update Nancy to 1.4.4
- Update Newtonsoft to 9.0.1
- Enable Websocket communication with UI

#### Todos
- [ ] Fix Mono Version unit tests

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by galli-leo** [comment]
I haven't had time yet to look through all changes, but I am guessing the deletions of a lot of files are normal? Also we should probably bump the health check to mono 4.8, since you cannot update with older versions.

**Comment by Qstick** [comment]
yea, the deletions are getting rid of old SignalR version that we were maintaining in repo and replacing with the nuget package instead. Will do on the mono bump.

**Comment by galli-leo** [comment]
Could you also update the error message to indicate auto updating is broken due to that mono version? And a more strong wording, something like: Your version of mono is badly outdated. Please upgrade as soon as possible to make sure Radarr works properly. Automatic updates are broken on this mono version!

**Comment by thezoggy** [comment]
just fyi: https://caniuse.com/#feat=websockets

**Comment by YipYup** [comment]
@galli-leo @Qstick 

Language proposal:

Your version of **mono** which is required by Radarr is deprecated and no longer supported. Core functionality of Radarr including automatic updates may be and will remain broken until you upgrade. You must manually upgrade your mono version to restore automatic update functionality.

**Comment by galli-leo** [comment]
Sounds good to me, what do you think @Qstick ?

**Comment by Qstick** [comment]
@galli-leo Yep, I like it. I'll update it. Sorry been out of it for a few weeks.

**Comment by Qstick** [comment]
@galli-leo Rebased

**Comment by Qstick** [comment]
Rebased, but I need to fix some tests on this before merged.

**Comment by Qstick** [comment]
Closing this, it’s in aphrodite

**Pull request closed without merging**
