### PR TITLE
Refactor MediaInfo tokens (fixes old tokens adds new stuff)

### PR DESCRIPTION
**Pull request by rfgamaral**
#### Database Migration
NO

#### Description
In a nutshell, this attempts to fix some issues with MediaInfo tokens and adds new interesting tokens:
- Updated MediaInfo to 18.08.1 (Windows/macOS);
- Fixes issue with VideoCodec not being properly used;
- Adds proper detection for most kinds of DTS and TrueHD streams (including DTS:X and Atmos);
- Adds support for `{MediaInfo 3D}` and `{MediaInfo HDR}` tokens;
- Fixed all related tests and added a couple more.

#### Todos
- [x] Some files containing DTS:X streams are being detected with `8.0` channels instead of `7.1`.
- [x] An exception is being logged due to audio channels (not sure if it's related to the issue above).
- [x] Fix failing unit tests due to all the changes to this refactor.

### CODE REVIEW

**Comment by rfgamaral** [comment]
FYI: Commit ef0ca17 contains a hacky fix to one of the things that were missing before the WIP could be removed on this PR. A temporary solution until MediaArea/MediaInfo/issues/299 is fixed and released.

**Comment by galli-leo** [comment]
Looks good! Thanks a ton for your prs!

**Comment by rfgamaral** [comment]
> 
> 
> Looks good! Thanks a ton for your prs!

No problem, just fixing/improving things that annoy myself in particular 😁 

Is there something preventing this one from being merged?

**Comment by galli-leo** [comment]
No, I just wanted to see the new CircleCI checks integration :). Sorry about that.

**Comment by galli-leo** [comment]
I just noticed the bitrate nominal part was removed. Can you add that back in?

**Comment by rfgamaral** [comment]
@galli-leo That wasn't removed per se.

The video `BitRate_Nominal` was being written to the `videoBitRate` variable, which was overwriting the video `BitRate` that was saved to the same variable.

So, either that was a mistake (and that's what I assumed and removed) or it should've been saved to a different variable and exposed as a different property other than `VideoBitrate` on `MediaInfoModel` (AFAIK, `MediaInfoModel` never had a property for "bitrate nominal".

**Comment by galli-leo** [comment]
@rfgamaral No sometimes BitRate is empty, hence BitRateNominal was used. You can find a recent PR explaining the change.

**Comment by galli-leo** [comment]
https://github.com/Radarr/Radarr/issues/2886

**Comment by rfgamaral** [comment]
Ok, I'll add it back :)

**Pull request merged**
