### PR TITLE
NEW: Custom Filters based on Availability

### LINKED ISSUE #2074: Add about to be released filter based on the Availability Delay
so, if i have Availability Delay set at -21 days, i would love to see movies that about to be released in -21 days...this filter will truly shine in IMDB popularity list

i am talking about this 

image

### PR DESCRIPTION
**Pull request by geogolem**
https://github.com/Radarr/Radarr/issues/2074

Step 1:
make the UI take into account AvailabilityDelay to make it consistent with RSS Decision Engine (edit --> this seems to be handled by another PR: https://github.com/Radarr/Radarr/pull/5406 - i have rebased this branch and so this issue is no longer addressed by this PR since it is no longer an issue)

Step 2: 
Add custom filter options for minimumAvailabilityDate with and without Delay

The filter names:
ConsideredAvailable ---> DateConsideredAvailable  (these always take into account the delay)
MinimumAvailability ---> MinimumAvailabilityDate  (these never take into account delay)

if delay = 0 .. the 2 dates above are identical.
MinimumAvailabilityDate will be 1 of InCinemas, Announced or Physical/Digital (Released) dates

Add ability to make the custom filter dates relative to currentdate

#### Database Migration
NO

#### Description

Examples:
Now the user could create a custom filters like the following:

"Recently Available" by setting DateConsideredAvailable in the last 30 days.
"Available Soon" by setting DateConsideredAvailable in the next 30 days.

You could also create a custom filter to see which movies are being impacted by the delay property by using both DateConsideredAvailable and MinimumAvailabilityDate in the same custom filter.

#### Issues Fixed or Closed by this PR

* Fixes #2074

### CODE REVIEW

**Comment by geogolem** [comment]
I had the thought to add a tooltip to the Status column for when "Not Available" is shown. The tooltip should show the DateConsideredAvailable. so if you hover the mouse over "Not Available" you will see the date radarr will consider it available.. 

This takes into account the MinimumAvailablity and the delay.. and is consistent with the rest of the PR.

I'll implement and add another commit to this PR soon.

**Comment by bakerboy448** [comment]
@geogolem you'll likely want to rebase once #5320 merges

**Comment by geogolem** [comment]
It looks like https://github.com/Radarr/Radarr/pull/5406 was just merged which  fixed the UI availability stuff to reflect the delay (which was the first part of this PR). I will rebase this PR...

**Comment by bakerboy448** [comment]
good luck; have fun with the merge conflict hell :D

give it 1 sec; another PR being merged

**Comment by geogolem** [comment]
> good luck; have fun with the merge conflict hell :D
> 
> give it 1 sec; another PR being merged

Thankfully, I don't think it was that bad.... I'll have to double check and test some more tomorrow though...

**Comment by geogolem** [comment]
@bakerboy448 : any chance of this getting merged anytime soon?

**Comment by geogolem** [comment]
I am going to close this pull request since it is basically replaced with: https://github.com/Radarr/Radarr/pull/10379

**Pull request closed without merging**
