### PR TITLE
New: Update MonoTorrent from nuget

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

#### Description
Remove copy/pasted code (that's 5 years old) and replace with monotorrent nuget.

#### Todos
- [x] Tests

### CODE REVIEW

**Comment by ta264** [comment]
Looks like we'd lose this fix:
https://github.com/Radarr/Radarr/commit/3bc6bf9e992b0c2e0f82591608f2037fdd313297#diff-8cb0d8f14f4315fb5c5c7110ebfc2254

**Comment by Qstick** [comment]
Kinda odd that is still an issue upstream after this long, but it seems to be https://github.com/mono/monotorrent/blob/fff50e2f3fede90b24b062efe77da989076bbf7f/src/MonoTorrent/MonoTorrent/Torrent.cs#L804 unless its fixed elsewhere in the code

**Comment by Qstick** [comment]
I'm good with pushing this in if we think that fix is not needed

**Comment by Qstick** [comment]
PR pushed upstream https://github.com/mono/monotorrent/pull/204. Can merge this after PR merge and release from monotorrent

**Comment by alanmcgovern** [comment]
@Qstick @ta264  - I'm not entirely sure what issue your original fix was solving. It looks like the issue could be that some client mis-encoded the 'nodes' value as a bencoded string instead of a bencoded list.

I've tentatively pushed a patch to handle that specific scenario gracefully. If the issue you're trying to resolve is different, please let me know what the issue is and we can get a better patch integrated :) 

https://github.com/mono/monotorrent/commit/b1f976a18fd42bef1c9c54a6bae654a3221283f6

**Comment by alanmcgovern** [comment]
(Also i am very excited to see you updating to the newer nuget!)

**Comment by Qstick** [comment]
@alanmcgovern thanks, the fix was pulled/inherited from the Sonarr side. Looking at the fix I’d assume you are correct, however @Taloth may be able to shed some light on the original issue they were running into in 2016?

**Comment by alanmcgovern** [comment]
Should this PR delete `MonoTorrent.cspoj` too? It looks like it's been left behind and it's empty

**Comment by ta264** [comment]
D'oh

**Comment by Taloth** [comment]
I definitely don't remember the details. 

But the commit date seems to match with this forum post: 
https://forums.sonarr.tv/t/sonarr-fails-to-download-torrent-files-from-rss-feed/9700
I presume the (now removed) hastebin/pastebin provided the necessary details to find the actual problem.

Sry that it wasn't documented better. Based on that I suspect it was just a 'this is a 0.1% edgecase but i'll throw in a patch'

**Comment by alanmcgovern** [comment]
The post says it's an invalidcast so I'll assume the incredibly vague BitTorrent DHT spec was interpreted differently by another dev. I assume they just compact-encoded the nodes instead of creating a list of lists. 

The patch I added should handle that case safely (ish) by ignoring malformed values in this case. 

Thanks!

**Pull request merged**
