### PR TITLE
Add PTP 'Other' category filtering with supporting release flags functionality

### PR DESCRIPTION
**Pull request by cymballistic**
#### Database Migration
NO

#### Description

Add PTP_Other tag to allow filtering of PTP's 'other' quality category. This would allow filtering of movies contained within PTP's 'other' quality section, but may not use the 'Extras' notation.

Also adds required functionality to extend release restrictions to flags as well as title.

### CODE REVIEW

**Comment by austinwbest** [comment]
Can this be squashed down?

**Comment by cymballistic** [comment]
Done.

> Can this be squashed down?

Done.

**Comment by bakerboy448** [comment]
conflicted

**Comment by Qstick** [comment]
We'll be reworking how flags work, closing this for now

**Pull request closed without merging**
