### PR TITLE
Add ability to unmonitor a movie after cutoff is met.

### PR DESCRIPTION
**Pull request by nate1280**
#### Database Migration
NO

#### Description
Add setting for feature.
Add ability to unmonitor a movie after cutoff is met.

#### Issues Fixed or Closed by this PR

* #718

### CODE REVIEW

**Comment by galli-leo** [comment]
We have discussed this, and came to the conclusion of not accepting this PR, for the following reasons:

1. If you have setup Radarr correctly, this feature is useless, since Radarr will not download releases when you have reached your cutoff.
2. This could confuse people, when they have the option download propers enabled. If you download a release and Radarr unmonitors the movie, Radarr will obviously not download propers anymore.
3. This will not work for the case where Radarr finds a better release when the last one it downloaded is still downloading. In that case, Radarr would still add the better release to the download client, although this option would make it seem like it shouldn't
4. Conversely, if we would unmonitor on download, Radarr couldn't download another release if the download fails or is removed for other reasons.
5. If you wanted to update your quality profiles and download better releases for all your movies, you would have to monitor them all again and then do that. This could again confuse users.

However, if you wanted to really do this, you could create a custom script to do this for you. Feel free to open a pr to pass something like `radarr_movie(file)_cutoffmet` to custom scripts for achieving that.

**Comment by RoChess** [comment]
@galli-leo, the problem is that your cutoff-met feature keeps failing for me over-and-over again (as well as at least three others who commented on #718 (jinxy88, bernardgut, blindguy, and who knows how many others who don't bother posting due to lack of empathy or not having a GitHub account).

The easiest to reproduce example of failure is when a perfectly good FraMeSToR release gets overwitten by an EPSILON-PROPER if it is not marked to unmonitored manually, but that's not as bad as a 70GB FraMeSToR REMUX getting replaced by a 20GB Blu-Ray. The problem is that it happens super random, and at such a low level that you yourself obviously never encountered it. I'm well aware that you require proper reproducible steps before you would consider looking at the code, but getting those has been a nightmare on such a sporadic issue that is driving me (and many others) insane.

Many programs have a "basic", "advanced-hidden-by-default", and a secret "i-want-to-void-warranty" section; is the latter a suitable alternative? I'm sure you want larger groups of people to try new features at a larger scale than beta-testers, so there's a lot of reusability for you with a hidden sections like that.

SABnzbd+ did the same, and only recently did they port their 'special' section due to popularity as a visible tab (with warning) under: /sabnzbd/config/special/ but it required being aware of the direct link on older versions to edit those unstable settings (or manually edit INI file).

Hoping you will reconsider the issue, or let me know how many votes it will require from people struggling with this issue as five users clearly isn't enough.

To summarize:

1. Existing system broken as elaborated with easiest to reproduce example (but many more use cases of it being broken exist)
2. That can be easily solved, and many existing settings are confusing for lot of users already, so feel free to reword it, or hide it as elaborated in detail above.
3. It would eliminate the mistakes currently made from say 1-in-10 to 1-in-100 then, and would be well worth it
4. Existing settings are causing issues as well, and if you looked at the PR the code will only do it AFTER successful download and Radarr is ready to link the final file
5. Those users, such as myself, that opt for that are used to that, manually upgrading profile and making one extra click to change it to monitored is easy compared to randomly getting the files you wanted/have deleted and replaced with unwanted versions

Your response to no. 4 makes me wonder if you even had time to look at the PR, which was well crafted to solve a niche problem, but was done in a proper setting-adjustable way. If your issue is with the confusion the extra setting might bring, then I fully support that, but consider offering a hidden-setting for those users who are fully aware of the ramifications.

The core code is in the 12-lines @ https://github.com/Radarr/Radarr/pull/3224/files#diff-28db5f60c55a9a5be58138d7b4c1e608R150 with all the other code changes required to add the setting and stay in line with Radarr's code style.

</rant>

**Comment by galli-leo** [comment]
> The easiest to reproduce example of failure is when a perfectly good FraMeSToR release gets overwitten by an EPSILON-PROPER if it is not marked to unmonitored manually, but that's not as bad as a 70GB FraMeSToR REMUX getting replaced by a 20GB Blu-Ray. The problem is that it happens super random, and at such a low level that you yourself obviously never encountered it. I'm well aware that you require proper reproducible steps before you would consider looking at the code, but getting those has been a nightmare on such a sporadic issue that is driving me (and many others) insane.

Just to make sure, you have auto download propers disabled, right? Yeah, I cannot reproduce it, however,  please send me some debug logs as well as screenshots of that movie's history page. That should still help and I can try to find out what's happening.

>Many programs have a "basic", "advanced-hidden-by-default", and a secret "i-want-to-void-warranty" section; is the latter a suitable alternative? I'm sure you want larger groups of people to try new features at a larger scale than beta-testers, so there's a lot of reusability for you with a hidden sections like that.

The problem isn't that it's especially advanced, it's that it conflicts with existing settings and in general the whole point of cutoff unmet. I know it doesn't work for you, however, even an advanced setting shouldn't conflict with existing ones to that extent.

I also want to avoid people just pointing to that setting if things don't work out. I have seen some software with advanced settings, where people just start recommending stuff that you shouldn't touch. An example might be changing that setting, when your download client doesn't correctly talk to Radarr. (A common config issue resulting in many downloads).

>It would eliminate the mistakes currently made from say 1-in-10 to 1-in-100 then, and would be well worth it

In my opinion, it could potentially decrease the error rate, but it could also increase it.

>Your response to no. 4 makes me wonder if you even had time to look at the PR, which was well crafted to solve a niche problem, but was done in a proper setting-adjustable way. If your issue is with the confusion the extra setting might bring, then I fully support that, but consider offering a hidden-setting for those users who are fully aware of the ramifications.

I looked at the PR code in great detail and I agree it was written very nicely and it used all the Radarr coding styles correctly (which I even fail to do some times). In my response, I wasn't suggesting that the PR is doing that. I was merely suggesting, that if we wanted to fix 3., the only option would be to unmonitor on download which would cause the issues mentioned in 4.

Furthermore, I encourage anyone to make a PR to add `radarr_movie(file)_cutoffmet` as an environment variable, so that one can easily make a small custom script to unmonitor movies. This way, there isn't a conflicting setting and that environment variable is a good idea anyways.

**Comment by RoChess** [comment]
@galli-leo thanks for taking the time for a detailed response, because I'm understanding of your viewpoint, but my frustration with Radarr deleting files I wanted to keep was too much to bear.

Radarr setting wise I do have auto download of PROPER set to 'on', because in the scenario of:

1. Movie.A.bla-bla.Group.A
2. Movie.A.bla-bla.Group.A-PROPER

I obviously want to end up with the PROPER.

The problem is when it is:

1. - Movie.B.bla-bla.Group.A
2. - Movie.B.bla-bla.Group.B-PROPER

Then I do **not** want the Group-B-PROPER, because I specifically enjoy releases from Group.A

With Radarr having knowledge of the `group` that was used to finish downloading to reach the cutt-off, maybe that can be used/added to avoid different-group-propers from replacing the file I want to keep?

Of course for me that doesn't solve the total issue, because I've had other unexplained cases of a movie getting replaced. However, upon further research (good thing I retained all the history) it seems that the other cases are due to a REPACK from Group.B replacing the file I wanted to retain from Group.A, or a MULTI.BluRay.Group.B replacing a REMUX.Group.A with REMUX being set as the cutt-off level above BluRay (that is the one that I noticed back in May 2018 to respond to the main thread).

Perhaps the strange anomaly I'm encountering all relates to auto download of PROPER active.

Of course that is a feature I would like to keep turned on, because I do not want to start watching a movie that is corrupt or missing parts.

PS: Reproduction will obviously be difficult without a way to publish test files to usenet in a specific order/time that will get indexed, but if memory serves me the manual import method of Radarr should follow the same rules. Copying a small file/trailer and renaming it accordingly should work, and I will otherwise try to detail the exact steps, but I won't have time until next weekend.

**Comment by galli-leo** [comment]
@RoChess Yeah that is something that Sonarr also lacks and I agree it makes much more sense. You could open a feature request so that gets tracked. I might have some free time over the next few weeks and maybe sketch up an implementation (no promises though).

**Pull request closed without merging**
