### PR TITLE
Added FolderPath to the Movie Webhook

### PR DESCRIPTION
**Pull request by adnanklink**
#### Description
Added the path to the movie webhook. The framework for this was already in place from the Sonarr fork. The test for this variable was already included in the test, probably since the fork as well.

### CODE REVIEW

**Comment by fhscholl** [comment]
You should probably give it a different name since FilePath will contain different content depending on which constructor was called.

**Comment by adnanklink** [comment]
The context is there though; movie webhook or 'WebhookMovie' is the constructor. The FilePath variable definition was also there before I did anything as well.

**Comment by fhscholl** [comment]
Right, but if the constructor is called with a movie it will be the full path of the movie directory. If it is called with the movie and a movieFile the same variable will instead be the full path to the video file.

This means that sometimes the FilePath sent by the webhook will sometimes contain a file path and sometimes contain the folder instead.

**Comment by adnanklink** [comment]
Funny thing is though, I don't think the constructor is ever called with a movie AND a movieFile. VS didnt find any references at least. The Ondownload/Upgrade events just call a separate constructor for WebhookMovieFile and include it in the payload resulting in no conflict, regardless of naming.

**Comment by fhscholl** [comment]
You make a valid point. The second constructor is left over from before I redid the webhook structure to match Sonarr. It's possible it isn't used anywhere now.

To that point FilePath can probably be removed since it is part of MovieFile output now anyway, but that is a commit for another time. 

I still like the name FolderPath for this anyway since it makes more sense.

**Comment by adnanklink** [comment]
@galli-leo The naming conflict was resolved.

**Pull request merged**
