### PR TITLE
New: Support On Delete Notifications for Emby

### LINKED ISSUE #4181: Connection - Emby # On delete
Hello,

**Is your feature request related to a problem? Please describe.**
When a movie is deleted from radarr, the emby connection doesn't offer to update the library of emby or jellyfin, so the movie is deleted from radarr, but still present on emby or jellyfin

**Describe the solution you'd like**
Add tick button "On delete" Be notified when movies are deleted
Change Update Library Update Library on Download & Rename & Delete

[AB#1842](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1842)

### PR DESCRIPTION
**Pull request by RobinDadswell**
#### Database Migration
NO

#### Description
Adds On Delete Notifications for Emby - this ideally needs testing by someone who has Emby/Jellyfin and running NFS/CIFS as their filesystem for movie storage

#### Issues Fixed or Closed by this PR

* Fixes #4181

### CODE REVIEW

**Review by Qstick — APPROVED** [review]

**Comment by neo-neo1** [comment]
> #### Database Migration
> 
> NO
> #### Description
> 
> Adds On Delete Notifications for Emby - this ideally needs testing by someone who has Emby/Jellyfin and running NFS/CIFS as their filesystem for movie storage
> #### Issues Fixed or Closed by this PR
> 
>     * Fixes [Connection - Emby # On delete #4181](https://github.com/Radarr/Radarr/issues/4181)

Thanks for the quick work. I will pull the develop branch and test it. If it works can it also be added to Sonarr? Same missing feature. Will reply back after testing.

**Comment by RobinDadswell** [comment]
> Thanks for the quick work. I will pull the develop branch and test it. If it works can it also be added to Sonarr? Same missing feature. Will reply back after testing.

This will only be on nightly in the app at the moment. As a word of warning there's a large number of changes by between master and nightly right now so going back to nightly may not be possible.

**Comment by bakerboy448** [comment]
It is not possible to go from nightly back to develop or master at this time.

**Comment by neo-neo1** [comment]
After testing I can confirm this works as expected. @RobinDadswell are you able to also make a pull request on Sonarr? Thanks again.

**Comment by RobinDadswell** [comment]
> After testing I can confirm this works as expected. @RobinDadswell are you able to also make a pull request on Sonarr? Thanks again.

have you opened an issue over there? If you haven't please do and reference this PR. Then either myself or someone from the Sonarr Dev team will get to it when we find some time.

**Comment by neo-neo1** [comment]
> > After testing I can confirm this works as expected. @RobinDadswell are you able to also make a pull request on Sonarr? Thanks again.
> 
> have you opened an issue over there? If you haven't please do and reference this PR. Then either myself or someone from the Sonarr Dev team will get to it when we find some time.

Done https://github.com/Sonarr/Sonarr/issues/4743

Thanks

**Pull request merged**
