### PR TITLE
New: Extend File naming option {MediaInfo AudioLanguagesAll} with count per language

### PR DESCRIPTION
**Pull request by Lonli-Lokli**
#### Database Migration
NO

#### Description
Fixing #4137

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR
#4137
* #

### CODE REVIEW

**Comment by Lonli-Lokli** [comment]
Sorry, I mentioned wrong ticket in commit message

**Comment by Qstick** [comment]
What's the use case here, what does it really do for you?

**Comment by Lonli-Lokli** [comment]
@Qstick my movie collection is not in English. And usually I prefer to have maximum amount of translations for the movie. Now it means I have to open existing file to see how many and what audio I already have when new release occurs, with this fix I will be able to see at least number of tracks from file name.without starting it and opening media props.

**Comment by Lonli-Lokli** [comment]
@Qstick is there update?

Also I would like to clarify why brackets [ and ] are included as formatting option - end user always can add whatever symbols he need into renaming format.

**Pull request closed without merging**
