### PR TITLE
Add Support for MDVDR Release Parsing

### PR DESCRIPTION
**Pull request by ItsME6969**
#### Database Migration
 NO

#### Description
Added: Support for Multi Disk releases
Added: Support for MDVDR

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* Fixes https://github.com/Radarr/Radarr/issues/6928

### CODE REVIEW

**Comment by bakerboy448** [comment]
Needs tests as well

**Comment by ItsME6969** [comment]
> Needs tests as well
How would I go about that? I'm certain the regex works.

**Comment by Qstick** [comment]
QualityParser tests for DVDR are here, essentially you'll want to add some sample release names here as test cases so that we confirm they are parsed correctly now (and in the future when we make changes)

https://github.com/Radarr/Radarr/blob/f6f949415c4d81c3849650b7e4b6a366bf874223/src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs#L76-L83

**Comment by ItsME6969** [comment]
@Qstick here are some test cases could you please test them out at your convenience? Thanks.
`Some.Movie.2020.PAL.2xDVD9
Some.Movie.2015.NTSC.2DVD9
Some.Movie.2009.PAL.2xDVD5
Some.Movie.2000.2DVD5
Some.Movie.1985.PAL.2xDVDR
Some.Movie.2020.PAL.2DVDR
Some.Movie.2005.PAL.MDVDR-SOMegRoUP`

**Pull request closed without merging**
