### PR TITLE
Increase session expiry time

### PR DESCRIPTION
**Pull request by 2omsnF**
#### Database Migration
NO

#### Description

Increase session expiry time.

There's a compelling reason to have a short expiry on sites with
senstive information like a bank, but if I forget to lock my computer
and someone starts messing with radarr, there is very little damage they
can do.

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

### CODE REVIEW

**Comment by onedr0p** [comment]
What if someone logs into a friends / public computer, doesn't think anything of it and forgets to sign out. I'd be happy knowing that in 7 days at least it would expire.

**Comment by 2omsnF** [comment]
In that case, you shouldn't check the "Remember Me" checkbox:

**Comment by Qstick** [comment]
Agree with @onedr0p, 7 days seems reasonable. One year is a step back on the security front IMHO

**Comment by 2omsnF** [comment]
> step back on the security front

I've looked more carefully at the Nancy code, and the expiry is just from the cookie expiry and not cryptographically enforced, so it's already not real security.

But now that I've noticed that, I can just go into the cookie and change 2019 to 2029 in the expiry date, so I don't even have to go through the hassle of a personal fork :smile:.

Anyway, feel free to close this. It's your project, and it seems like we have some unreconcilable differences in option on the appropriate level of security for this kind of application.

I appreciate you both taking the time to read over and provide feedback on this PR! I've really enjoyed using Radarr, so thank you for all your hard work.

**Pull request closed without merging**
