### PR TITLE
Pull Sonarr commit 'Generalized RateLimit logic to all indexers based on indexer id'

### LINKED ISSUE #5891: Pull Sonarr commit 'Generalized RateLimit logic to all indexers based on indexer id'
Pull https://github.com/Sonarr/Sonarr/commit/d898f55660657e9f6cd57ce4659e36c5046cd8f8

```
git cherry-pick -ex d898f55660657e9f6cd57ce4659e36c5046cd8f8
```

This commit has 3 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### PR DESCRIPTION
**Pull request by RobinDadswell**
Sonarr Pull
Pull commit:
Generalized RateLimit logic to all indexers based on indexer id

Issues Fixed or Closed by this PR
Fixes #5891

### CODE REVIEW

**Review by Qstick — DISMISSED** [review]
Looks good, can you change the comment to auto link the issue before merge by using `Fixes`
```
Issues Fixed or Closed by this PR
Fixes #5891
```

**Comment by RobinDadswell** [comment]
Rebased to latest commits @Qstick  will need a re review please :)

**Comment by Qstick** [comment]
Can you get rid of the merge commit? Rebase

**Comment by RobinDadswell** [comment]
Done; I think it's this button that did it 
image

**Comment by Qstick** [comment]
Yea that will usually add a merge commit to update it which we try to avoid

**Comment by RobinDadswell** [comment]
That would make sense... the best bit is it was a blank merge commit!

**Review by Qstick — APPROVED** [review]

**Pull request merged**
