### PR TITLE
Fix #1958 import rarbg substitles

### LINKED ISSUE #1958: .srt file(s) in subfolders are not being imported.
RARBG movie convention puts subtitle files in a folder called 'Subs' within the movie folder. Radarr only seems to see subtitle files for import in the main movie folder, not subfolders, so the RARBG subtitle files are ignored and not imported.

### PR DESCRIPTION
**Pull request by jpogs**
#### Database Migration
NO

#### Description
RARBG files are not being imported because of its file naming convention ie 2_English.srt

Note: I initiated this fix again as I've been seeing requests to include this update. Please note that Radarr does not import SRT subtitles as is (or with the original filenames) because it needs to ensure filenames follow naming conventions and so that media players are able to load the subtitles accordingly. See https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/ for details. The end-to-end import logic for SRT subtitles is far from perfect and will have limitations because it caters to the needs of a variety of user scenarios (please see limitations below). Before logging a bug please consider the case of other users who need this update and assess whether the behavior affects the application's functionality (or if it is just cosmetic in nature ie. "I don't like the filename")

Limitations: 
1. There is a need to suffix the subtitles with an index or number to support multiple versions (2_English, 3_English). Otherwise multiple versions will be named the same (movie.en.srt) and will therefore overwrite each other. As a result other versions will be discarded. Solution is to name the 1st substitle it encounters as movie.1.en.srt and so on...
2. Radarr does not contain a comprehensive list of ISO languages so subtitle languages that are not in this list will not be identified. Identified languages will be suffixed accordingly (movie.1.en.srt, movie.1.fr.srt) while unknown languages will follow the movie name (movie.1.srt, movie.2.srt)

#### Issues Fixed or Closed by this PR

* #1958
* #5378

### CODE REVIEW

**Comment by Qstick** [comment]
@jpogs Thanks, Third time is a charm right :)  Can you add some test cases to this so we know it behaves as it should.

**Comment by jpogs** [comment]
Hi @Qstick, would you be so kind to re-trigger the test pipeline? I believe the test failed due to an IOException unrelated to the code change...

**Comment by Qstick** [comment]
Can you squash this? Thanks

**Comment by douglas24** [comment]
Hope you don't give up on adding subfolder subtitles support @jpogs

**Pull request closed without merging**
