### PR TITLE
New: Add Spain to list of Certifications

### LINKED ISSUE #5374: Add Spain country for Certification Country
Like #5351. It would be great if Spain were added as a certificate provider.

I have seen that it is not included from Servarr, but it is available in TMDb.

Best Regards. A Radarr lover 😍.

### PR DESCRIPTION
**Pull request by danimart1991**
#### Database Migration
NO

#### Description
Add Spain to list of Certifications based on https://github.com/Radarr/Radarr/commit/6beb8c8b05847e08eb775032048e37350dd350f3

#### Screenshot (if UI related)
image

image

#### Issues Fixed or Closed by this PR

* Fixes #5374

### CODE REVIEW

**Review by Qstick — APPROVED** [review]

**Comment by danimart1991** [comment]
Little fix. Alphabetical order.

**Comment by Qstick** [comment]
It's fine on the UI, but keep it last on the Enum backside (I screwed that up on mine).

**Comment by danimart1991** [comment]
> It's fine on the UI, but keep it last on the Enum backside (I screwed that up on mine).

What logic follow the enum order?

**Comment by Qstick** [comment]
As added, they get a unique id based on the order in the enum... we convert it to the value to store in the db, so it doesn't really matter that much in this case. But as a regular practice it's not good.

**Pull request merged**
