### PR TITLE
Allow profiles to select release that contains MULTI tags

### PR DESCRIPTION
**Pull request by Filimindji**
#### Database Migration
YES, but not sure if it works with existing databases.

#### Description

I added an "Allow MULTI" option on Profile view that allow the decision engine to select a release that contains the MULTI tag.

Use case : 
- The user profile is set to french.
- The Allow MULTI is set to true.

On french tracker, it's common to find this kind of file : "Nocturnal.Animals.2016.MULTi.1080p.BluRay.x264-ANONA".

The file contains french audio, but it's not explicit in the file name.

The "Allow MULTI" option allow the engine to download this release even if the LanguageParser return english.

#### Todos
- [ ] Tests, not sure about how to deal with that.

#### Issues Fixed or Closed by this PR

* https://github.com/Radarr/Radarr/issues/892
* https://github.com/Radarr/Radarr/issues/848

### CODE REVIEW

**Comment by kriegalex** [comment]
I agree with option 3 proposed by galli-leo. The reason being that tags (even if they are mostly standardized) are linked to teams and while some teams upload everywhere, some other are linked to a particular tracker, especially on non English trackers. 

Option 3 allows you to target specific indexers and more clearly define tags:

- Spanish tracker gets MULTI as English + Spanish when spanish is not specified
- If you add support to differentiate VFF (France) from VFQ (Quebec), French tracker A gets MULTI as VFQ + English while french tracker B get MULTI as VFF+VFQ+English (because a team from tracker B you like does it that way and you use preferred tag for this team).
- German tracker gets.... You understand the deal

**Comment by galli-leo** [comment]
@kriegalex I would actually like to implement all three options, if that wasn't clear from my comment.

**Comment by Filimindji** [comment]
Hello.

Even if I see some cases where options 1 and 2 could be usefull, I don't
see how they can help to solve the current issue that is 'Some entries are
only tag with Multi, and it's lead Radarr to set them as English, by
default, and profiles that are set to anything but english will not be able
to download them'.

**Comment by galli-leo** [comment]
@Filimindji Well if we add proper multi support, (like in 3. for example) releases could have multiple languages, so profiles should have that too. 2. Is more of an extension of 1.

**Comment by lucianot54** [comment]
@galli-leo Why make it complicated? You want add "multi"tag on Indexer but when you make a config, you don't have different language trackers. And you will create relation between Indexer and language detection. 
Add "multi" in Profiles is more simple and it's just an optional option.

Your options will be nice for a few people but for french people, it's a real problem and @Filimindji  solve it.

**Comment by Filimindji** [comment]
Hello @lucianot54 

From my point of view, this pull request solve the issue, but I also agree that a Per Indexer should be better. Unfortunatly, I'll not have more time to implement this before next year.

I think this pull request could be merge 'as is' for a quick fix, and improved later :  If the MULTI option in Profile is set and the Indexer declare a language compatible with the Profile, then, the movie will be downloaded. And if there is no language declared in the indexer, it will just download the movie, like in this pull request.

**Comment by kriegalex** [comment]
@all I also think that if teams don't make an effort to unify their naming schemes, we can release as much quick fixes as we want, even a complete refactor like galli-leo wants, the problem will never be solved unless you implement machine learning on subtitles and audio tracks. Even then, subtleties between language variances (i.e. VFF/VFQ) would be (maybe?) hard to recognize.

To avoid having too much parameters, checkboxes, etc... the "automation" community should also talk to teams that create this problems. It is I think much less efforts than coding to account for all possible scenarios. In this case, @Filimindji I think that talking to the teams that use MULTI without VFF, VFQ or VF2 would be as efficient as patching Radarr (or Sonarr) :)

**Comment by alxdc9** [comment]
It's probably far from ideal but has anyone already implemented a language check after having completed the download ? 

That way, if you can't find the multi + VF that you are looking for but you find a release which only has multi with no specific language, you could still try to download it, check the audio track language and blacklist it if it doesn't match.

**Comment by Filimindji** [comment]
@alxdc9 : In my humble opinion, to download the movie just to check if it is an acceptable movie is not the best way to handle this.

@kriegalex : Talking to teams do not look like a robust solution either :-)

**Comment by alxdc9** [comment]
@Filimindji If you're using a tracker that commonly has french with their MULTI tag but does not specify any language in the filename, I guess you have to download it to know. Your proposal with ALLOW_MULTI will anyway download a release that only states MULTI in the filename. Since it has already downloaded it, at least check that it really contains the language you are looking for. Otherwise, you may end up with a language that you do not want.

**Comment by Filimindji** [comment]
@alxdc9 : Well, you got me. That's right it's a guess, and I'm pretty sure to not been disappointed because I trust the tracker will check the release and provide the language I expect when I see the Multi tag. But it's a guess. And from this perspective your proposition could help to check the video automatically.

**Comment by nikogaug** [comment]
Hello,
I'm not sure that I understand everything. Is this issue already commit ? in the develop version ?
If yes, how can we had multi to french profile ?

Great thanks,
Nikogaug

**Comment by galli-leo** [comment]
Closing this. It will be fixed by project metis / custom qualities.

**Pull request closed without merging**
