### PR TITLE
New: Parse Open Matte as Edition

### PR DESCRIPTION
**Pull request by erri120**
#### Database Migration
NO

#### Description
To make James Cameron happy.

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* Fixes https://github.com/Radarr/Radarr/issues/1414#issuecomment-489077620

### CODE REVIEW

**Comment by Qstick** [comment]
Do you have some example releases for this?

**Comment by erri120** [comment]
> Do you have some example releases for this?

Some results from a quick search:
image
image
image
image

**Review by Qstick — APPROVED** [review]
Thanks

**Comment by TRaSH-** [comment]
I actually would like to see the original source they used for this
and if it's really open matte or just imax or a fan res

**Pull request merged**
