### PR TITLE
Update to favicon section, according to

### PR DESCRIPTION
**Pull request by hotio**
http://realfavicongenerator.net/

#### Database Migration
NO

#### Description
Some updates to make it work on all platforms/browsers.

Don't merge immediately, I'm first gonna test the AppVeyor build...

### CODE REVIEW

**Comment by hotio** [comment]
Seems to be working great now.

**Comment by hotio** [comment]
Although it works ok, doing this
```
curl http://server:7878/Content/Images/favicon/browserconfig.xml
```

gives this:

```
{
  "message": "Sequence contains more than one matching element",
  "description": "System.InvalidOperationException: Sequence contains more than one matching element\n  at System.Linq.Enumerable.SingleOrDefault[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x42118a60 + 0x0018f> in <filename unknown>:0 \n  at NzbDrone.Api.Frontend.StaticResourceModule.Index () [0x000a5] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\Frontend\\StaticResourceModule.cs:55 \n  at NzbDrone.Api.Frontend.StaticResourceModule.<.ctor>b__3_0 (System.Object x) [0x00000] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\Frontend\\StaticResourceModule.cs:25 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x422d5840 + 0x0014f> in <filename unknown>:0 "
}
```

and an error in the log

**Comment by galli-leo** [comment]
Is the browserconfig stuff important? Or should I wait before a merge?

**Comment by hotio** [comment]
It's for when you add a tile to the Windows Start Menu, you'll get a nice looking tile...
The file manifest.json is for when you add a shortcut on the homescreen, so it looks more like a native app.
It all works properly, also on android, except when accessing browserconfig.xml and manifest.json directly, instead of receiving the file you get an error, chrome, chrome on android and edge however seem to deal with it just fine.

But it are all cosmetic changes.

naamloos

**Pull request merged**
