### PR TITLE
Update LoadingMessage.js

### PR DESCRIPTION
**Pull request by McGeaverBeaver**
Remove - "   'Congratulations! you are the 1000th visitor.', "

#### Database Migration
 NO

#### Description
 remove the joke  'Congratulations! you are the 1000th visitor.' on loading

#### Screenshot (if UI related)
none taken, this is a loading message on UI 
#### Issues Fixed or Closed by this PR

https://github.com/Radarr/Radarr/issues/5523#issuecomment-760659428

### CODE REVIEW

**Comment by tr1ckz** [comment]
I don't understand how adding a spam like message seems funny or a good idea. My wife called me over scared because she thought she got a virus.

**Comment by angrycuban13** [comment]
Lol

**Comment by angrycuban13** [comment]
I just want to be sure I understand, the `1000th visitor` is a bit much but you are totally ok with `'HELP! I'm being held hostage and forced to write these stupid lines!'`?

**Comment by bakerboy448** [comment]
So just did some testing on my instance right now, the message was up for 2-3 seconds, not even long enough to screenshot.

**Comment by angrycuban13** [comment]
> I don't understand how adding a spam like message seems funny or a good idea. My wife called me over scared because she thought she got a virus.

Sounds like you should educate your wife?

**Comment by Krandor1** [comment]
On my setup I see it more then 2-3 seconds but it’s also very clear it’s from Radarr so I don’t pay the messages any mind. 

Don’t have an issue with it staying or with it being removed.  I consider it irrelevant.

**Comment by angrycuban13** [comment]
I vote that we add this please

**Review by tr1ckz — APPROVED** [review]

**Pull request closed without merging**
