### PR TITLE
New: Release Group Custom Format

### LINKED ISSUE #7086: Pull Sonarr commit 'New: Option to show release group column on series list'
Pull https://github.com/Sonarr/Sonarr/commit/f1d07f74ee05587dc7baf7d55a6504cea18cb273

```
git cherry-pick -ex f1d07f74ee05587dc7baf7d55a6504cea18cb273
```

This commit has 14 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#2702](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2702)

### PR DESCRIPTION
**Pull request by danimart1991**
#### Database Migration
NO

#### Description
New: Release Group Custom Format

#### Screenshot (if UI related)
image
image

#### Todos
- [ ] Tests
- [] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Closes #7086

### CODE REVIEW

**Comment by bakerboy448** [comment]
Not sure on Release Group as a Custom Format condition.  It duplicates what can already be done with Release Title. Defer to Q and Ta on that.

**Comment by Qstick** [comment]
Release group as Custom format is fine

Release group on index and filters is no go, we're not going that until after the multi file work is sorted.

**Comment by danimart1991** [comment]
This feature is already in Sonarr. Adaptation for multifile in Radarr should be as simple as I already did for multiple episodefiles => multiple release groups column in Sonarr. 🤔

**Comment by danimart1991** [comment]
It's frustating, but I understand the challenging work that is to introduce more than one file per movie. So don't worry, I can wait. 😉

**Comment by danimart1991** [comment]
Updated to only add Release Group Custom Format

**Review by Qstick — APPROVED** [review]

**Pull request merged**
