### PR TITLE
Fixed: multiline in table view

### PR DESCRIPTION
**Pull request by hotio**
#### Database Migration
NO

#### Description
Fixes the movie list view in table view to not use two lines because of "links"

### CODE REVIEW

**Comment by Qstick** [comment]
Does this also fix mobile devices, doesn't seem as though it would. Should we conditional hide links section based on screen size?

**Comment by hotio** [comment]
This does nothing for mobile devices, just a quick way to get everything back onto one line.

**Comment by Qstick** [comment]
Ok I'll test tonight and approve as a quick fix. Probably don't need to spend alot of effort in fixing everything given a new UI is being worked

**Comment by hotio** [comment]
Indeed

**Comment by Qstick** [comment]
This doesn't seem to fix it reliably for me. I have to increase to 1478 px for cases when title column is max width, profile column is max width, etc..

To test, add a long movie like `The Englishman Who Went Up A Hill But Came Down A Mountain`, then assign it an absurdly long profile name, and make sure that it or another movie on screen is downloaded status instead of missing status you get something that looks like:

image

vs at even 1475:

image

**Comment by hotio** [comment]
Probably missed it because I don't have such a long movie name. 1478 is fine with me

**Comment by Qstick** [comment]
Ok, either that or limit the width of the title column more. if you throw update up I'll push it in

**Comment by hotio** [comment]
done

**Pull request merged**
