### PR TITLE
Fix: A small bug fix for items loading as undefined in organize modal

### PR DESCRIPTION
**Pull request by PatrickGHanna**
#### Database Migration
NO

#### Description
I updated both backbone.backgrid.js and backbone.backgrid.selectall.js.
I also sorted the returned collection from  getSelectedModels()

before:
radarrbug

after:
radarrfix

#### Todos
let me know if you thinking any tests are necesarry to this change. The only thing I see that is testable is the sort I perform, which I would be happy to test if you think its necessary.
- [ ] Tests

#### Issues Fixed or Closed by this PR

* # The organize modal under movie editor was pulling undefined items for items that weren't on the current page.

* # The organize modal was not showing items by their sortTitle

### CODE REVIEW

**Comment by galli-leo** [comment]
Hmm. Did you notice any issues occurring with other parts after updating Backgrid.js and SelectAll.js? I mean there shouldn't be, but you never know.

**Comment by PatrickGHanna** [comment]
Let me do some ad hoc testing today and I will get back to you.

**Comment by PatrickGHanna** [comment]
@galli-leo The issue is still occurring if you filter the grid to hide selected items (eg. announced filter) and attempt to organize. This wasn't introduced by this PR, but it didn't fix it either. I will take a look at why this is occurring and if its a code change I can make on Radarr's end or if its a bug in the 3rd party library.

**Comment by PatrickGHanna** [comment]
@galli-leo  I found a much simpler way of achieving this fix without needing to update the libraries. (although I think it wouldn't hurt if we updated those libraries in another PR)

**Comment by galli-leo** [comment]
Is this pr ready to be merged? Looks good from my side.

**Comment by PatrickGHanna** [comment]
This should be good to go.

**Comment by galli-leo** [comment]
@PatrickGHanna Also there are no JS tests as far as I know.

**Pull request merged**
