### PR TITLE
New Language: Spanish (Latin America) - Lang 37

### LINKED ISSUE #3467: split spanish language
imo the spanish langunage (said language does not exist tho) need to be split in two or more

1. spanish-español or castellano
2. spanish-latino or latino 

this is a issues because the accent and certain words, for example coger in spain means to take, while in argentina means to fuck 

every bit of content is doubled once for span and second time latino america

:smiling_imp:  if you want to start a flame war just that the simpsons are better in latino or castellano 

[AB#876](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/876)

### PR DESCRIPTION
**Pull request by Miguel1422**
#### Database Migration
NO

#### Description
Split spanish language into Spanish and Spanish (Latin America), this allows better results when searching in either language 
#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* Fixes #3467

### CODE REVIEW

**Comment by austinwbest** [comment]
Can you squash this to a single commit since they are both part of the same change

**Comment by Miguel1422** [comment]
@austinwbest Done

**Comment by bakerboy448** [comment]
Not to be that guy... but "New: Split Spanish Language into Spanish Latino and Spanish" or similar would be a bit better so it shows on the release notes

**Comment by Miguel1422** [comment]
@bakerboy448 @austinwbest Done

**Comment by bakerboy448** [comment]
- conflicts
 - Lang 32 in use by https://github.com/Radarr/Radarr/pull/6385 | use Lang 33

**Review by bakerboy448 — DISMISSED** [review]
update language # & etc for conflicts

**Comment by Miguel1422** [comment]
@bakerboy448 Done

**Comment by bakerboy448** [comment]
rebase; do not merge

**Comment by Miguel1422** [comment]
@bakerboy448 Done

**Comment by bakerboy448** [comment]
conflicts

**Comment by Miguel1422** [comment]
@bakerboy448 Done

**Comment by bakerboy448** [comment]
bump lang to 37

**Comment by Miguel1422** [comment]
@bakerboy448 Done

**Comment by BakasuraRCE** [comment]
Hi! This feature is really needed, Spanish without Latin just makes all software unusable for Latin people

**Comment by austinwbest** [comment]
> Hi! This feature is really needed, Spanish without Latin just makes all software unusable for Latin people

Unusable? None of the apps where localized for years and sonarr still isn't. You just started trying to use radarr and not sonarr and can't figure it out?

**Comment by friki67** [comment]
Hello. I've been following this from the beginning.The differences between Latin America Spanish and European Spanish are so, that every single film or tv series is dubbed in both variants. They sound different, they are very different idioms from the same language.
I've seen some languages added after this enhancement has been proposed. Indeed, the conflicts resolved and to resolve are because of them. Why is this taking so long?
What are the difficulties/problems to resolve? How to help to set this up?

**Comment by rubenixnagios** [comment]
I hope this will be done at some point, really needed

**Comment by bakerboy448** [comment]
It's once again conflicted and needs to be rebased

**Comment by caroku** [comment]
Sonarr has already added latin american spanish, hope that helps.

**Comment by yayitazale** [comment]
Come on please almost 2 year from first PR....

**Review by RobinDadswell — APPROVED** [review]

**Pull request closed without merging**
