### PR TITLE
Add Tags to existing Movie from multiple Import Lists

### LINKED ISSUE #5299: New/Old movies in Trakt lists aren't tagged
**Describe the bug**
I add a Radarr tag to any Trakt List configuration window. The new movies added from these Lists doesn't have been tagged. Not even the old movies that was previously added.

**To Reproduce**
1. Go to 'Settings -> List -> Add/Modify a Trakt List'
2. Add a tag to 'Raddar Tags' field.
3. [Optional] Authenticate again + Test
4. Save the form
5. Press update all movies button or wait for a new movie to be automatically imported.

**Expected behavior**
New and Old movies that are in the Trakt Lists must have the associated tags. 

image

**Screenshots**
image

**Platform Information (please complete the following information):**
 - OS: Debian 10 + Docker
 - Package Version: nightly-6f1d5a0-640 by hotio
 - Radarr Version: 3.0.0.3987

### PR DESCRIPTION
**Pull request by danimart1991**
#### Database Migration
NO

#### Description
When Movie imported from List is already in Database, check if has the tags of the list and if not, add it to the movie in database.

#### Todos
- [ ] Tests
- [ ] Translation Keys
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #5299

### CODE REVIEW

**Comment by austinwbest** [comment]
But it wasn't added by the list if it was existing 🤔

**Comment by bakerboy448** [comment]
But it wasn't add by the list because it already exists?

Seems we have a chicken and the egg 🤔

**Comment by austinwbest** [comment]
> But it wasn't add by the list because it already exists?
> 
> Seems we have a chicken and the egg 🤔 

More of an understanding or purpose

Is the tag meant to signify what was added automatically from a given list or only to show if a movie is contained in a list. Really a @Qstick decision there.

Former nulls this change where as latter justifies it.

**Comment by bakerboy448** [comment]
Gonna play devils advocate and suggest both, so we add an advanced toggle and leave whatever the initial purpose is as default

**Comment by Qstick** [comment]
Yea lists were never meant to update anything, they were just a convenient way to add movies automatically. And tags are meant to go with items that were added by that list. 

Before we start updating properties for existing movies and library items from lists I think we need to think about 
1) Do we want to go down this path (it feels messy having lists edit whatever they want) 
2) How it should work and how best to layout the UI/Options/Etc without it being confusing.....
3) How we want to manage edits/upgrades without it becoming a support nightmare ("My movies keep randomly changing, Radarr is broken" says user with 5 lists with different settings)

**Comment by danimart1991** [comment]
I understand your reasoning. In fact, another option that I propose is to not only delete a movie if it is deleted from the list (option that already exists), but to include, only delete the movie if it is not in any list, and if it is in at least one , delete only the tag from the list where it was deleted.

I would like to advance this feature with your tips and steps.

**Comment by danimart1991** [comment]
Updated to upstream. Ready for the review.

**Comment by Mushin** [comment]
> I personally dont agree with tagging existing things that where not added from the list just because they exist on the list currently. The tagging was intended to be for what the list does add, not does contain.

What about adding an option to the list config, something like "keep tags updated from this list (on/off)"? And default to off, so behaviour is the same.

**Comment by RobinDadswell** [comment]
> 3. How we want to manage edits/upgrades without it becoming a support nightmare ("My movies keep randomly changing, Radarr is broken" says user with 5 lists with different settings)

I am not sure if this has been addressed, but it would definitely need to be before this was merged.



> I personally dont agree with tagging existing things that where not added from the list just because they exist on the list currently. The tagging was intended to be for what the list does add, not does contain.

I agree with @austinwbest on this one, lists are not a sign of what is there but a sign of what has been added into a list.

**Pull request closed without merging**
