### PR TITLE
New: Reject Files at Import if they are Multi-Part for now

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
Instead of trying to import and only getting part, reject movie if they look like multi-part until we add support

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR
Relates to #145
* #

### CODE REVIEW

**Comment by kevindd992002** [comment]
Is this not yet implemented? I recently downloaded the two-disc copies (two files at around 70GB each) of the three LOTR movies using torrent and Radarr imported just Disc 2 for all. I thought it should not import them and stay with an orange warning in the GUI? Here are the logs from Radarr if needed:

https://www.dropbox.com/s/1qa18jcezci4s2t/radarr_logs.zip?dl=0

**Comment by bakerboy448** [comment]
@kevindd992002 
It was merged on 7/22/2020

no one is going to look through a whole zip of presumably several log files.

how are the files labeled?

**Comment by kevindd992002** [comment]
Sorry, I thought it's standard to provide the log files.

The files are labeled like so:

image

image

**Comment by bakerboy448** [comment]
Typically logs are useful yes

but just the line of the issue and nice hundred line plus chunks around it and in a Pastebin....no one around here is going to be downloading a random zip and most don’t like download text files either  (no offense)

anyway, it looks we may not be accounting for multiple movie files within two sub folders of a movie download

rather than split by name they are named crappily and in Disc 1 and Disc 2 sub folders

**Comment by kevindd992002** [comment]
Yeah, that makes sense.

Ok, so is this kind of directory/file naming structure not supported in the future? And is supporting multi-part movies in the works for Radarr?

**Comment by austinwbest** [comment]
Quick look at the tests from this PR, it is looking for multiple part files in the same location and basing it on that. It isn't spanning multiple folder + multiple parts.

**Comment by kevindd992002** [comment]
So no chance of improving the logic to accommodate this type of directory/file structure?

**Comment by austinwbest** [comment]
> So no chance of improving the logic to accommodate this type of directory/file structure?

I don't think anyone said that. Just wasn't covered previously if all that was mentioned

**Pull request merged**
