### PR TITLE
New Language: Bengali - Lang 37

### PR DESCRIPTION
**Pull request by kristof-mattei**
#### Database Migration
 NO

#### Description
Added Bengali, due to some erronious detections on my system. 

Based on https://github.com/Radarr/Radarr/commit/2823099237fd3973322a562aafc3649c775d9369

#### Todos
- [x] Tests
- [ ] ~~Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)~~
- [ ] ~~[Wiki Updates](https://wiki.servarr.com)~~

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by austinwbest** [comment]
I think 32 is used by another PR (Hungarian or something that was discussed in the last couple months), you may want to search for that. I'm on my phone so can't at the moment.

**Comment by kristof-mattei** [comment]
Sounds good.

**Comment by bakerboy448** [comment]
- Lang 32 in use by https://github.com/Radarr/Radarr/pull/6385 
 - Lang 33 in use by https://github.com/Radarr/Radarr/pull/6415
 - Lang 34 in use by https://github.com/Radarr/Radarr/pull/6522
 - Lang 35 in use by https://github.com/Radarr/Radarr/pull/6522
 - Lang 36 in use by https://github.com/Radarr/Radarr/pull/6564
use lang 37

also squash the PR down to 1 simple commit as well

**Review by bakerboy448 — DISMISSED** [review]
update language # & etc for conflicts

**Comment by kristof-mattei** [comment]
@bakerboy448 done

**Pull request closed without merging**
