### PR TITLE
UI cleanup, fixes and consistency

### PR DESCRIPTION
**Pull request by jamesmacwhite**
#### Database Migration
NO

#### Description

I'm still working through all the UI elements, but thought I'd push what I've been doing so far. I'm basically going through the handlebars files `.hbs` and fixing up issues where I find them, particularly.

* Consistent titles/field values (capitalisation)
  * I think the best rule to follow is write headings/sections title etc that are currently capitalised like "Movie Naming" as "Movie naming" and then CSS to display it as such, because technically, capitalising is styling thing.
* Improving accessibility with icons `aria-hidden` in places
* Trying to get the code consistent with the following rules:
  * No closing tags on `img` `input` fields (HTML 5 doesn't need them)
  * Closing icons with `</i>`
  * Closing `<div>` elements with `</div>` not `/>`
* Making `title` values consistent with punctuation
* Fixing hanging tags/syntax issues in places which have gone unnoticed previously
* Minor grammar alternations in places
* Fix indentation where needed for better readability.

In addition to the above:

* Allow 128x128 logo to appear in the medium breakpoint
* Added woff2 fonts for faster loading in browsers that support it
* Also fixed the local src name of the Ubuntu Mono regular font
* Fixed `</body>` being closed before JavaScript in `index.html`

Let me know if this is something worth continuing!

### CODE REVIEW

**Comment by hotio** [comment]
Not that my input is worth much, but I think it's worth continuing. It should look just as beautiful beneath the bonnet...

**Comment by galli-leo** [comment]
Seems worth continuing to me! Let me know when you are finished with this pr, so I can merge it.

**Comment by jamesmacwhite** [comment]
Will do! Thanks.

**Comment by jamesmacwhite** [comment]
@galli-leo The PR as it stands should fix up a lot of the inconsistency in terms of labels, headings etc in the UI. I haven't modified the "TV/Series" stuff as its not used. I guess at some point its probably worth trying to remove some of the unused UI handlebars stuff, but probably not now!

Because the UI is massive, I'm sure a few visits will be needed to fully get things right, but hopefully this is a good start!

I have tried to test sections to ensure I haven't regressed anything, but if you notice anything let me know!

**Comment by galli-leo** [comment]
Thanks a lot!

**Comment by galli-leo** [comment]
Seems like this pr caused a few ui regressions (See https://github.com/Radarr/Radarr/issues/1984, https://github.com/Radarr/Radarr/issues/1989, https://github.com/Radarr/Radarr/issues/1988) Can you take a look? For now I reverted your commit.

**Comment by jamesmacwhite** [comment]
@galli-leo. Apologies will review ASAP.

**Pull request merged**
