### PR TITLE
New: Change Add Movie Monitor Selection from Dropdown to Checkbox

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
~~Change monitor true/false to yes/no~~
Change Add Movie Monitor From Dropdown to Checkbox
#### Todos
- [X] Translation Keys
- [x] Fix Value of Monitor won't save

#### Issues Fixed or Closed by this PR

Fixes #5263

### CODE REVIEW

**Comment by Qstick** [comment]
Why not just turn this to a checkbox?

**Comment by bakerboy448** [comment]
Would a checkbox fit in though?

The rest is mostly drop downs as well. 

Also may change when multi-file support is worked?

**Comment by Qstick** [comment]
It's a checkbox for the same info on Edit Movie modal... I think its more user friendly, I'd go checkbox route for now we can evaluate if other options come up later

**Comment by bakerboy448** [comment]
image
looking good

**Comment by bakerboy448** [comment]
@Qstick if you have any ideas on the monitored value apparently not saving now, I'm all ~~ears~~ eyes

It also appears to initially default to a grayed out checkbox? possibly related?

But that should be all that remains with this

**Review by Qstick — APPROVED** [review]

**Pull request merged**
