### PR TITLE
New: Add Localizaton to Radarr

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
No

#### Description
Add Localization to Radarr UI and Backend Strings

- Uses .json asset files
- Logs stay English (for Support reasons)
- Initial PR localizes SideBar and HealthChecks (more components to follow)

#### Todos
- [x] Weblate Server for Community Driven Translation
- [x] LocalizationService Tests
- [x] Weblate Repo Access Tests
- [ ] Weblate Permissions Tests
- [x] Rebase - Move Weblate live (tranlsate.servarr.com)

### CODE REVIEW

**Comment by foXaCe** [comment]
how to integrate the french translation team?
my weblate account is the same as github

**Comment by Qstick** [comment]
I’ll turn you on to translate

**Comment by Qstick** [comment]
@foXaCe you should be good to go

**Comment by foXaCe** [comment]
thank you

**Pull request merged**
