### PR TITLE
New: Rename Protocol to Preferred Protocol in Delay Profiles

### LINKED ISSUE #7278: Pull Sonarr commit 'New: Rename Protocol to Preferred Protocol in Delay Profiles'
Pull https://github.com/Sonarr/Sonarr/commit/704cf7aebef60b5b5bdf1ea55d68d4a3394396e0

```
git cherry-pick -ex 704cf7aebef60b5b5bdf1ea55d68d4a3394396e0
```

This commit has 3 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#3121](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3121)

### PR DESCRIPTION
**Pull request by bakerboy448**
Closes #7278

(Based on sonarr 704cf7aebef60b5b5bdf1ea55d68d4a3394396e0)

#### Database Migration
YES - XXXX | NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)
- [ ] Figure out if sonarr front end changes are needed and cherry/reset if needed

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Review by Qstick — CHANGES_REQUESTED** [review]
No go, this will also change the column headers for queue and interactive search... need to put a bit more work in to get it right.

**Comment by bakerboy448** [comment]
fixedup and [common]ed

**Comment by Qstick** [comment]
Where’s the rest of the Sonarr commit?

**Comment by bakerboy448** [comment]
> Figure out if sonarr front end changes are needed and cherry/reset if needed

So we do need that refactoring then eh

**Pull request closed without merging**
