### PR TITLE
Correctly Parse German Scene Bluray REMUXes

### PR DESCRIPTION
**Pull request by ItsME6969**
#### Database Migration
NO

#### Description
Correctly Parse German Scene REMUXes based on German scene rules --> https://scenerules.org/t.html?id=2016_DE_AVC.nfo

#### Issues Fixed or Closed by this PR

* Fixes https://github.com/Radarr/Radarr/issues/6307
* That issue wasn't really fixed

### CODE REVIEW

**Comment by Qstick** [comment]
I have 0 familiarity with German Scene releases, What's DL/ML stand for?

Also, I'm debating keeping this a separate Regex from the `RemuxRegex`

**Comment by Qstick** [comment]
No, definitely not a new quality or profile. Just a new Regex in `QualityParser` to keep things clean. 

Outside of that, Maybe it's just the way things are for German Scene, but I still don't understand how this naming is correlated to REMUX quality releases.

**Comment by Qstick** [comment]
Yea certainly, I saw the difference from the beginning. That doesn't mean it makes sense. Nothing we'll solve here though.

I'm fine sending this in after we split the Remux regex in quality parser. If you don't quite understand what I'm getting at with that, I can throw it in tomorrow on top of your change.

**Comment by JBou** [comment]
I think he means to split it up like i did back then when i submitted a PR to fix this: https://github.com/Radarr/Radarr/pull/6999/commits/fe1ef8177d9430b433db3d7b488dada51d9b5fb5

**Comment by Qstick** [comment]
Yep, exactly what I meant. Thanks @JBou

**Comment by Qstick** [comment]
@ItsME6969 did you still want me to button this up, or were you going to fix it quick?

**Comment by Qstick** [comment]
You have trailing whitespace in QualityParser

**Comment by Qstick** [comment]
@ItsME6969 That should do it..

I'll squash it after it builds

**Pull request merged**
