### PR TITLE
Add Download_Id to On Download/On Upgrade

### PR DESCRIPTION
**Pull request by adnanklink**
#### Description
Feature based on equivalent Sonarr feature. Add an additional enviornment variable for the download id from the torrent client for the custom post processing script feature. The variable name is 'Radarr_Download_Id' with the description 'The hash of the torrent/NZB file downloaded (used to uniquely identify the download in the download client).

* #

### CODE REVIEW

**Comment by galli-leo** [comment]
Did Sonarr also add a testcase for this?

**Comment by adnanklink** [comment]
They did not, no. Sonarr had a HistoryTest that called the event 'EpisodeImportedEvent' where it required an additional argument to be added. Radarr's Test have no such calls to ' MovieDownloadedEvent'.

**Comment by galli-leo** [comment]
Ah ok.

**Comment by pminnebach** [comment]
Once merged, can you also update the docs/wiki please.

**Comment by galli-leo** [comment]
@pminnebach You can edit the wiki yourself :)

**Comment by levic92** [comment]
@adnanklink what download client are you using? I am not getting the download ID from deluge, the code looks a little different from what Sonarr is doing. Is there something missing?

**Comment by adnanklink** [comment]
@levic92 It is definitely working for me in deluge. I have a script that will go in and delete the matching torrent in deluge and have had no problems. Keep in mind that only completed download handling torrents will have a download id. Manually importing from the torrent client will not have a download id.

**Comment by levic92** [comment]
@adnanklink I think I see my problem, I thought this change was in the newest version in the GUI 0.2.0.870, but now comparing the dates it doesn't look like it. Can you give me any tips on how to get the version with this change?

**Comment by adnanklink** [comment]
@levic92 switch to the 'nightly' branch in radarr?

**Comment by levic92** [comment]
Great everything is working now. Thanks @adnanklink

**Pull request merged**
