### PR TITLE
New: Add headers in webhook connection

### LINKED ISSUE #10552: Add headers in webhook connection
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd like to interact with an external API that requires an authentication token in the headers.

### Describe the solution you'd like

A new field to add custom headers in the webhook connection setup.

### Describe alternatives you've considered

Writing a script that will receive these webhooks and send them back with the required headers, but that would be quite annoying to do for every webhook.

### Anything else?

If this is something that could be merged, I'd be happy to submit a PR to implement it.

### LINKED ISSUE #10672: Pull Sonarr commit 'New: Add headers setting in webhook connection'
Pull https://github.com/Sonarr/Sonarr/commit/78fb20282de73c0ea47375895a807235385d90e3

```
git cherry-pick -ex 78fb20282de73c0ea47375895a807235385d90e3
```

This commit has 6 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### PR DESCRIPTION
**Pull request by gauthier-th**
#### Database Migration
NO

#### Description
This PR adds a new field to add custom headers in the webhook connection. It uses a `TextTagInput` to store each value.
However, this `TextTagInput` has a drawback: it makes it impossible to have a header value with a comma, but I haven't figured out a cleaner/simpler way of implementing it.

#### Screenshot (if UI related)
image

#### Todos
- [ ] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #10552
* Closes #10672

### CODE REVIEW

**Comment by bakerboy448** [comment]
Should go upstream in sonarr first and then flow downstream ideally

**Comment by gauthier-th** [comment]
> Should go upstream in sonarr first and then flow downstream ideally

I did the PR here in radarr because it was discussed here (and because I need it on radarr).
But I can close this one and submit it sonarr if you want to, or submit the same PR to sonarr later.

**Comment by gauthier-th** [comment]
@bakerboy448 is this supposed to mean that I can close this PR, and open it upstream?

**Comment by bakerboy448** [comment]
The Servarrbot would try to cherry-pick and PR downstream once committed to sonarr.

If there's conflicts it'll skip the PR and only GHI - leaving the cherry-picking to a human.

In other words - 

- PR upstream to Sonarr
- if it'd be a clean pick to Radarr could close this PR and let the bot handle it
- if not - leave this up and best case it goes before upstream. Worst case it just goes to close the bot's GHI.

**Comment by bakerboy448** [comment]
landed upstream; good to go once re-aligned with upstreams feedback.

would suggest just reseting in develop and cherry-picking upstream if it's easier

https://github.com/Radarr/Radarr/issues/10671

**Comment by gauthier-th** [comment]
Hi. Do you have any ideas on how to solve these failed tests?

**Pull request merged**
