### PR TITLE
Update parsing french movies

### PR DESCRIPTION
**Pull request by onedr0p**
#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* #892

### CODE REVIEW

**Comment by Ninjouz** [comment]
Releases like "XXX.2016.MULTi.TRUEFRENCH.1080p.BluRay.x264-LOST" are seen as French release since the parser regexp changes while the primary langage is still English.

I think that MULTI should always be considered as English first.

The feature for handling differents langages is the last missing pieces for Radarr :)

**Comment by galli-leo** [comment]
@Ninjouz The problem is handling multiple languages is really hard. IIRC a multi release could also be French / German. So we can't really know that. I plan to add an option though to consider Multi always also as English / Language of your profile.

**Comment by JocPelletier** [comment]
The MULTI option is a really good idea. Do you expect this to be available soon?

**Comment by galli-leo** [comment]
@JocPelletier No idea.

**Pull request merged**
