### PR TITLE
Fix InvalidOperationException

### PR DESCRIPTION
**Pull request by LooseSeal2**
#### Database Migration
NO

#### Description
Fixes IOE because more than 1 record returns now from the default installation.
#### Issues Fixed or Closed by this PR
* #3758

### CODE REVIEW

**Comment by LooseSeal2** [comment]
@Qstick can you please test and merge this in to fix automatic imports failing due to quality having more than 1 result.

**Comment by Qstick** [comment]
Thanks, I'll look at it tonight

**Comment by Qstick** [comment]
This should hopefully be fixed by 78cac9fcfa07b35e59ac467a7713c9100dc349f3, can you test 2.0.0.2069 when its finished building

**Comment by LooseSeal2** [comment]
@Qstick It looks like some items auto imported early this morning but some of them didn't. I'll continue to monitor it.

**Comment by Qstick** [comment]
@LooseSeal2 thanks, I need to make a couple more tweaks to the logic tonight, but hopefully the errors are gone

**Pull request closed without merging**
