### PR TITLE
New: Added links to wiki and examples from add/edit custom tags dialog

### PR DESCRIPTION
**Pull request by WoLpH**
#### Database Migration
NO

#### Description
Added links to wiki and examples from add/edit custom tags dialog

### CODE REVIEW

**Comment by WoLpH** [comment]
@Qstick would you mind merging this before the stalebot kills it? :)

**Comment by onedr0p** [comment]
I got you fam.

**Comment by onedr0p** [comment]
@WoLpH feel free to add this to the aphrodite branch too :)

**Comment by WoLpH** [comment]
@onedr0p took me a while to look at this but I'm not sure which css rules work for de aphrodite branch honestly. 

I found the code here:  https://github.com/Radarr/Radarr/blob/aphrodite/frontend/src/Settings/CustomFormats/CustomFormats/EditCustomFormatModalContent.js

But I'm not sure if a simple copy/paste of the HTML would work. I haven't investigated further but is the new branch using bootstrap as well? i.e. will the `help-block` class have any effect?

**Comment by onedr0p** [comment]
Aphrodite is using react, not sure about the rest but it's a complete UI redesign so it will be different code to apply this.

**Comment by WoLpH** [comment]
I'm aware of that, but it depends on the css and components that are used. I might look at this in the future but for now it's a little too involved for me to dive in

**Pull request merged**
