### PR TITLE
qBittorrent API V2 Support

### PR DESCRIPTION
**Pull request by zero77**
https://github.com/Radarr/Radarr/issues/3309

Moved To https://github.com/Radarr/Radarr/pull/3356

### CODE REVIEW

**Comment by zero77** [comment]
@teejo75 
> I don't think those calls in your PR are correct. Not all of those commands are under the /app endpoint.

I have had a look and they should all work now.

But these are the ones i am least sure about:
> /api/v2/app/setLabel		https://github.com/Radarr/Radarr/pull/3328/files#diff-9e741359eca49f3f307566f6c0ed7984R137

> /api/v2/torrents/upload		https://github.com/Radarr/Radarr/pull/3328/files#diff-9e741359eca49f3f307566f6c0ed7984R95

> /api/v2/torrents/torrents	https://github.com/Radarr/Radarr/pull/3328/files#diff-9e741359eca49f3f307566f6c0ed7984R64

**Comment by Qstick** [comment]
Instead of just changing all calls over to new API, you should likely have some logic around which calls to make based on version. Currently your PR kills all support for QBit versions prior to 4.1. If we think that install base is tiny now and that previous versions have been phased out then it would be ok, if not we need to look at some extra logic like we do for nzbget.

**Comment by zero77** [comment]
@Qstick 
That was mentioned already hear #3309.
> Unless i am mistaken, qBittorrent has supported API v2 for a while but, the next stable update will be dropping the older APIs and moving to v2 completely.

Additionally, i have never used C# before and i think it may be beyond my current level of knowledge.

**Comment by zero77** [comment]
@Qstick @teejo75
The recommendation from the qBittorrent Devs, is to drop support for API v1 and move to API v2 completely.
see: https://github.com/qbittorrent/qBittorrent/issues/10160

**Comment by onedr0p** [comment]
My suggestion would be to add a new download client that is just the new version of qBittorrent, call it `qBittorrent 4.x`. Then we can deprecate the old one at a later time. This will still allow for older versions of the software and also allow users to use the new one.

What do you guy think?

**Comment by Qstick** [comment]
Why not cache the qBit version and make calls based on the client version? Then it becomes all automatic. Same as currently being done for nzbget on a smaller scale. I suppose it comes down to if it’s just endpoint changes or if responses are also different?

**Comment by zero77** [comment]
@Qstick 
> Why not cache the qBit version and make calls based on the client version? Then it becomes all automatic. Same as currently being done for nzbget on a smaller scale. I suppose it comes down to if it’s just endpoint changes or if responses are also different?

That sounds like it would be more streamlined and cause less issues for users.

How could that be implemented, would an if statement at the top of QBittorrentProxy.cs that loads other API 1 or 2 based on your qbittorrent vershon, work.

**Comment by itsbebbo** [comment]
If you need to add a preference option to select v1 or v2 (Probably the simplest way rather than having to code to parse the supported version number in qBittorrent) then simply add lines near the end of QBIttorrentSettings.cs similar to:

`[FieldDefinition(9, Label = "Use API V1", Type = FieldType.Checkbox, HelpText = "Use qBittorrent API V1 (Leave unchecked to use default V2).")]`
`public bool UseApiV1 { get; set; }`

and also one a little higher up under public QBittorrentSettings():

`UseApiV1=False;`

You can then use the true / false value in the proxy code to determine which api to call...

If you need more assistance I can probably spend some time on this.

**Comment by itsbebbo** [comment]
@zero77 / @Qstick - Owing to the number of changes I feel are needed to make the code workable (some of the passed parameters have also changed from V1 to V2 and would also need to be re-configured / checked on return) I feel you should simply wrap V1 in an outer IF as mentioned above and then we can code just for V2 below. This will save multiple IF's throughout the code which would make it very messy and hard to read. Personally, I would revert these changes, add the outer IF and then duplicate the V1 code into the V2 ELSE section making all necessary changes.

The change I mentioned above to the Settings.cs file can still be made.

As stated, do you want me to flesh out the basics of the code and then return it to you for testing? I'm not brill with GIT having only just started using it and not sure if I can edit or jointly assist on the same PR???

**Comment by zero77** [comment]
@itsbebbo 
> Personally, I would revert these changes, add the outer IF and then duplicate the V1 code into the V2 ELSE section making all necessary changes.

>  I'm not brill with GIT having only just started using it and not sure if I can edit or jointly assist on the same

Hi thanks for your help, you seem to have a much better understanding than me of the best way to proceed and what's required. Also, to my knowledge you cannot edit an existing PR.

So, if it's easier for you i can close this PR, and add your suggested code above at the end of QBittorrentSettings.

**Comment by itsbebbo** [comment]
I’m in the middle of editing a version now - I have set up the build on my Mac and just got it working - I have implemented the Settings item and now just doing the V2 stuff. Up to you regarding the PR - can you change owner on it???

**Comment by zero77** [comment]
@itsbebbo 
> I’m in the middle of editing a version now - I have set up the build on my Mac and just got it working - I have implemented the Settings item and now just doing the V2 stuff. 

Excellent, thanks.

> Up to you regarding the PR - can you change owner on it???

I have no idea but, i will have a look.

**Comment by itsbebbo** [comment]
I had to change my initial plan as I realised that it is a class module and therefore can’t wrap it in an IF. I will try and get it running tonight and update...

**Comment by itsbebbo** [comment]
@zero77 I've completed and tested (most) of the code against V2 of the API. Now to get it back to you!

**Comment by zero77** [comment]
@itsbebbo 
> I've completed and tested (most) of the code against V2 of the API. Now to get it back to you!

That was quick
> Up to you regarding the PR - can you change owner on it???

After looking into this, i couldn't find any way to change the owner the PR.
I think the easiest way to proceed is for you to create a new PR.
You said you are new to github, do u need a hand on creating a new PR (pull request).

**Comment by itsbebbo** [comment]
I was bored!

Yes, can you direct me on linking it to the issue as well please?


Thanks

**Comment by zero77** [comment]
@itsbebbo 
Hope this gives you an idea of what to do to create a pull request.
https://github.com/zero77/Create-A-PR-On-Github

> can you direct me on linking it to the issue as well please

This bit is easy, just paste the url of your pull request in the comment box.

**Comment by itsbebbo** [comment]
@zero77 - Thanks - Completed the PR #3356

**Comment by zero77** [comment]
Moved To https://github.com/Radarr/Radarr/pull/3356

**Pull request closed without merging**
