### PR TITLE
Improved matching for Surround Sound formats

### PR DESCRIPTION
**Pull request by RandomNinjaAtk**
Enables matching for DD/AC3 5.1 surround sound formats. 

Previously AC3 and DD would not match using the existing default configuration.

#### Database Migration
YES | NO

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by fryfrog** [comment]
This is my surround sound regex and `DD` is intentionally not matched, like `DTS`. It is intended for the *good* surround sound. So if you're going to add DD/AC3, you should probably let DTS in too.

**Comment by RandomNinjaAtk** [comment]
I was planning on writing another PR to fix that once this one was accepted. So the final string would look like:

DTS.?(HD|ES|X(?!\D)|[5-9])|TRUEHD|ATMOS|DD(\+|P|).?([5-9])|(EA|A)C3.?([5-9])

Which would allow DTS 5.1 to be accepted as surround sound. Because I noticed afterward that it's also not.  

The basis of this Custom format is simply surround sound, so the type should not really matter, and could argue that AAC 5.1, Opus, and flac formats should also possibly be included...

Almost a second format could be used that would be HD surround sound, which would be locked to, truehd/dts-hd/x etc...

**Comment by fryfrog** [comment]
I only ever see `DTS`, not `DTS 5.1`.

**Comment by fryfrog** [comment]
Also, if you just want `DD`, then `DD(\+|P|).?([5-9])` is overkill. Just like `DD.?` would cover it, right?

**Comment by RandomNinjaAtk** [comment]
> Also, if you just want `DD`, then `DD(\+|P|).?([5-9])` is overkill. Just like `DD.?` would cover it, right?

No that will not work, 

> I only ever see `DTS`, not `DTS 5.1`.

The basis is surround sound and technically DTS could be 2.0 which would not qualify as surround sound. Same for DD/AC3. However DDP is an exception to that rule because it has built in upmix to 5.1 even at 2.0 level.

**Comment by fryfrog** [comment]
Ah, sounds like you've got it pretty well thought out. Thanks for improving it. :)

**Comment by RandomNinjaAtk** [comment]
Updated the PR to include all surround sound formats for improved matching

**Comment by fryfrog** [comment]
```
TRUEHD|ATMOS|((DD(+|P|))|((EA|A)C3)|DTS|FLAC|OPUS|AAC).?([5-9]|HD|ES|X(?!\D))
```

Okay, so I'm not great at regex...

But won't this *miss* just `ddp` or `dd+` w/o a number of channels after? I would also like to see `DTS` closer to the `HD|ES|X` that it pairs with, for better understanding.

**Comment by rg9400** [comment]
In my opinion, rather than trying to combine everything into one catch-all surround sound format, create a few and let users mix and match as they choose. If they want to create the "ultimate" surround sound CF, then they can add all of these predefined conditions into a single CF. This also has the added benefit of letting users see which formats were matched to which movies rather than trying to reverse engineer it from a single messy regex. I use the below with
`{Mediainfo AudioCodec}` and `{Mediainfo AudioChannels}` and the testing has been excellent. For best results, making each of them mutually exclusive is ideal. 

Examples

DTS-HD: `dts.?(hd|ma|es)`
Basic Dolby Digital: `DD[ .]?([1-9])|(?<!e)ac3`
Basic DTS: `DTS[ .]?([1-9])`
Dolby Digital Plus: dd(p|\+)|eac3
DTS-X: `dts(\-|\.)?x(?!\d)`
FLAC: `FLAC`
TrueHD ATMOS: `TrueHD|ATMOS`
Low Channel Count: `(?<!repac)(\D|\s)[1-4]\.[0-1]|Stereo|\bMono\b`
5.1 Surround Sound: `(\D|\s)[5-6]\.[0-1]`
7.1 Surround Sound: `(\D|\s)[7-8]\.[0-1]`

If we want to get really fancy, we can create combos of multiple conditions
DD+ ATMOS (lossy): requires above DD+ condition, requires ATMOS: `ATMOS`, requires negation of TrueHD: `TrueHD`
TrueHD (non-ATMOS): requires TrueHD: `TrueHD`, requires negation of ATMOS: `ATMOS`

**Comment by RandomNinjaAtk** [comment]
> In my opinion, rather than trying to combine everything into one catch-all surround sound format, create a few and let users mix and match as they choose. If they want to create the "ultimate" surround sound CF, then they can add all of these predefined conditions into a single CF. This also has the added benefit of letting users see which formats were matched to which movies rather than trying to reverse engineer it from a single messy regex. I use the below with
> `{Mediainfo AudioCodec}` and `{Mediainfo AudioChannels}` and the testing has been excellent. For best results, making each of them mutually exclusive is ideal.
> 
> Examples
> 
> DTS-HD: `dts.?(hd|ma|es)`
> Basic Dolby Digital: `DD[ .]?([1-9])|(?<!e)ac3`
> Basic DTS: `DTS[ .]?([1-9])`
> Dolby Digital Plus: `dd(p|\+)|eac3`
> DTS-X: `dts(\-|\.)?x(?!\d)`
> FLAC: `FLAC`
> TrueHD ATMOS: `TrueHD|ATMOS`
> Low Channel Count: `(?<!repac)(\D|\s)[1-4]\.[0-1]|Stereo|\bMono\b`
> 5.1 Surround Sound: `(\D|\s)[5-6]\.[0-1]`
> 7.1 Surround Sound: `(\D|\s)[7-8]\.[0-1]`
> 
> If we want to get really fancy, we can create combos of multiple conditions
> DD+ ATMOS (lossy): requires above DD+ condition, requires ATMOS: `ATMOS`, requires negation of TrueHD: `TrueHD`
> TrueHD (non-ATMOS): requires TrueHD: `TrueHD`, requires negation of ATMOS: `ATMOS`

This is more of a feature request, you should open a issue as a feature request to create more default formats. This PR is only for updating the existing one to improve the existing format.

**Comment by MollyBe** [comment]
You last edit referred to:
````
TRUEHD|ATMOS|((DD(\+|P|))|((EA|A)C3)|DTS|FLAC|OPUS|AAC).?([5-9]|HD|ES|X(?!\D))
````
but due to the error in there I've assumed you meant,
````
TRUEHD|ATMOS|((DD(\+|P|))|((EA|A)C3)|DTS|FLAC|OPUS|AAC).?([5-9]|HD|ES|X(?!\D))
````
Strange behaviour this regex doesn't match Anon.2018.1080p.BluRay.DTSx264-SbR in regex101 but it does in radarr aphrodite.

My regex below doesn't match Anon.2018.1080p.BluRay.DTSx264-SbR in regex101 or in radarr aphrodite.

https://regex101.com/r/CCcKBo/1

image

In regex101 there are false positives and missed matches with your current regex.

I would suggest we use:
````
DTS.?(HD|HD.?([5-9])|ES|X|X.?([5-9]))\b|TRUEHD|ATMOS|DD(\+|P).?([5-9])|EAC3.?([5-9])
````
This regex doesn't change match preference from what it currently is, it corrects missed matches and removes false positives.

If we do change the match preference to include DD/AC3/FLAC/OPUS/AAC 5.1+ surround sound we could do something like:
````
TRUEHD|ATMOS|((DD(\+|P|))|((EA|A)C3)|DTS|FLAC|OPUS|AAC).?([5-9]|HD|HD.?([5-9])|ES|X|X.?([5-9]))\b
````

I think we should change this preset to include all surround sound, as it is called Surround Sound.

Another preset for the best surround sound would be ideal.

**Comment by Qstick** [comment]
@MollyBe You probably want to use regex storm if you are comparing for Radarr as they use the .net regex engine, regex101 doesn’t.

@fryfrog how do we want to handle this one?

**Pull request closed without merging**
