### PR TITLE
Fix MediaInfoFormatter: Unable to format audio channels using 'AudioC…

### PR DESCRIPTION
**Pull request by LooseSeal2**
#### Database Migration
NO

#### Description
Quick fix for Input format exception. 

#### Todos
- [ ] Explore alternative fixes.

#### Issues Fixed or Closed by this PR
* #3758

### CODE REVIEW

**Comment by LooseSeal2** [comment]
@Qstick I'm not sure a more robust fix is needed at this time, but regex matching may be better.

**Comment by Qstick** [comment]
What version of mediainfo do you have? packaged version or something else?

**Comment by Qstick** [comment]
Also, can you run mediainfo outside of Radarr on one of these files and post? If the 3rd digit is something like overhead channels then this fix would not accurate. Also we should make it more robust to handle all cases when we could have 3 digits

**Comment by LooseSeal2** [comment]
@Qstick I'm using LSIO docker. I'm certain it is overhead channels (atmos). I'll do that and let you know.

**Pull request closed without merging**
