### PR TITLE
New: Add Slovak Language - Lang 35

### PR DESCRIPTION
**Pull request by Gylesie**
#### Database Migration
NO

#### Description
Added support for Slovak language. 

#### Todos
- [x] Tests

### CODE REVIEW

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
- Language 35 is in use by #6522  use 36
- commit message should be `New: Add Slovak Language`

**Comment by Gylesie** [comment]
@bakerboy448 Done.

**Comment by Gylesie** [comment]
Hopefully, third time's the charm :D

**Comment by Gylesie** [comment]
@bakerboy448 Rebased.

**Comment by Qstick** [comment]
@Gylesie go ahead and change this back to 35, we'll push it in today. The other PR for 35 needs a bit of tweaks in our system to support correctly.

**Comment by Gylesie** [comment]
> @Gylesie go ahead and change this back to 35, we'll push it in today. The other PR for 35 needs a bit of tweaks in our system to support correctly.

@Qstick Changed back the language id to 35. Hopefully this PR will get merged. Thanks!

**Review by RobinDadswell — APPROVED** [review]

**Pull request merged**
