### PR TITLE
Parse Polish language

### PR DESCRIPTION
**Pull request by tenshiak**
#### Database Migration
 NO

#### Description
As in the title. Almost no-one names their torrent "polish".

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

Fixes nothing.

### CODE REVIEW

**Comment by Qstick** [comment]
Can you add some test cases to the language parser unit tests? 

Let me know if you need help finding the right place.

**Comment by tenshiak** [comment]
I've added bunch of test cases

**Review by Qstick — APPROVED** [review]

**Comment by Qstick** [comment]
Can you rebase? There’s a conflict

**Comment by tenshiak** [comment]
Fixed

**Comment by tenshiak** [comment]
@Qstick mention me if something else needs to be done

**Comment by Qstick** [comment]
Looks fine save for the merge commit, but I can squash it going in.

**Comment by Qstick** [comment]
@tenshiak spoke to soon, you have a trailing white space issue in LanguageParser that is failing backend analysis

**Review by Qstick — APPROVED** [review]

**Comment by Qstick** [comment]
Rebased to remove merge commit and resolve conflict

**Review by Qstick — APPROVED** [review]

**Pull request merged**
