### PR TITLE
Fixed: Misc Extra File Improvements

### LINKED ISSUE #2547: Radarr deleting existing .nfo files
I have Radarr set up to upgrade movies, but not for metadata.  As a result, when it does upgrade a movie for me, it deletes the existing .nfo files.  

I do not want to use the metadata setting in Radarr because I use meta\<browser\> for that due to greater interactivity.  Is there a setting I am missing or is this a bug?  I had a look at the metadata and media management tabs and nothing obvious jumps out.

This issue only started about a week or so ago and I am on the nightly builds so I am guessing it started around version 0.2.0.961, currently I am on 0.2.0.972.

Thanks.

### LINKED ISSUE #2556: Name Backdrop -fanart and not banner
**Description:**

This issue is a followup of Issue #167  (Merged Pullup #2506 ).
The problem is that downloaded artworks by **Kodi (XBMC) / Emby Metadata Downloader** are not named correctly based on [default Kodi naming scheme](https://kodi.wiki/view/Movie_artwork)

Currently, the downloaded artworks are named like this in each movie's folder:
NFO File: `<NameOfVideoFile>.nfo`
Poster: `<NameOfVideoFile>-poster.jpg`
Fanart: `<NameOfVideoFile>-banner.jpg` (wrong)

But, based on Kodi Wiki and by assuming single movie in each directory, the naming should be like this:
NFO File: `<NameOfVideoFile>.nfo`
Poster: `<NameOfVideoFile>-poster.jpg`
Fanart: `<NameOfVideoFile>-fanart.jpg`
Actor Image: `.actors/<FirstName>_<LastName>.jpg`

**Radarr Version:**
0.2.0.954

**Mono Version:**
4.8.1 (Stable 4.8.1.0/22a39d7 Tue May 2 23:55:41 UTC 2017)

**Debug Logs:**
Not needed

### LINKED ISSUE #2639: Radarr Deleting Extra Files
**Radarr Version:**
0.2.0.995

I have been using a program called Media Center Master for years. It organized my collection, and downloaded a lot of extras for my movies. Things like subtitles, banners, and disc art.

I have only had Radarr running for an hour, so I am extremely new. However, I have it set to monitor my movies. It downloaded one, and instead of just replacing the movie, it deleted all of my extras in the folder, and then moved the updated movie in.

Can a feature be added that will allow me to keep all of my extras, and just replace the actual movie?

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
Yes

#### Description
This changes mapping of backdrop images to Fanart instead of Banner
Added DB migration so that current images are changed and movie refresh is not required.

#### Issues Fixed or Closed by this PR
Fixes #2556 
Fixes #2639 
Fixes #2547 
* #

### CODE REVIEW

**Comment by Qstick** [comment]
Yes, I’ll update the migration to 145 as well. Nice work on the PTP cookie handling btw.

**Comment by Qstick** [comment]
Added a few things here:
- should recognize all Kodi image types now as metadata instead of other.
- should always send metadata to recycle instead of perm delete (pull from Sonarr).
- changed migration to 145 since you are using 144 for PTP.
- read nfo to determine kodi/scene (from Sonarr).
- rename scene nfo to nfo-orig when appropriate (from Sonarr).
- preserve watch status in nfo (from Sonarr).

**Comment by galli-leo** [comment]
Have you given some thought about deleting only movie file extra data? Or will these changes not delete e.g. movie nfos and images?

**Comment by Qstick** [comment]
Yes, I'd like to switch Kodi metadata over so that Images are only linked to the Movie itself and not MovieFile. This will fix issues with deletion, however metadata images named as <moviefilename>-poster.jpg will not be renamed during a movie rename. Radarr metadata will be created as poster.jpg or fanart.jpg, but existing metadata images will not be renamed on upgrade or rename.

**Comment by tusharbhutt** [comment]
It's now saving the extrafanart andextrathumbs folders, but still deleting all other image files (poster, folder, bacdrop, background, etc).  Oh yes, and the .nfo file too but I think that's still a to-do?

**Comment by Qstick** [comment]
What version are you running?

**Comment by tusharbhutt** [comment]
Radarr Ver. 0.2.0.1008

**Comment by Qstick** [comment]
OK, yea that has none of these PR changes in it. This PR should fix those deleting file issues.

**Comment by tusharbhutt** [comment]
Oh, good to know!  I thought the nightly builds pulled the latest, glad I was wrong.

**Comment by galli-leo** [comment]
@Qstick PTP Branch is merged, so this should be good to go when you fix the merge issues.

**Comment by Geek16432** [comment]
I'm still seeing this behavior on 0.2.0.1120

**Comment by gnoling** [comment]
I'm seeing this as well. I've had to stop using Sonarr as it's trashing my carefully curated metadata and artwork.

**Comment by jimmy327** [comment]
I HATE bringing up old posts, but this is still happening in Version 0.2.0.1450
I've spent the past several hours manually pulling all of my poster images back down from backup and manually editing Plex as I just finished updating several hundred files to find out Radarr has been deleting everything in the folder when it updates.  

I know this is an old post, but is there a fix somewhere?

**Comment by AwesomeAustn** [comment]
This is still happening and I'm on version 3.0.0.3964.

**Comment by bakerboy448** [comment]
@AwesomeAustn please don't comment on closed, 3yr old issues

**Pull request merged**
