### PR TITLE
New: Support AKA release titles

### LINKED ISSUE #3748: Unable to import movie with 'AKA' in the title
**Describe the bug**
Movies with 'AKA' in the title/filename do not get imported into Radarr after being downloaded.

I am able to add a movie (The Taste of Money 2012 -- https://www.imdb.com/title/tt2106670/) and download it from the indexer. The torrent client successfully downloads it, however cannot be imported and automatically added to Radarr. It does not appear in the 'Activity' tab, although in 'History' for the movie I can see it was downloaded.

**To Reproduce**
1. Add The Taste of Money (2012) to Radarr
2. Download the release Do-nui.mat.AKA.The.Taste.of.Money.2012.576p.BluRay.x264-HANDJOB from PTP
3. Observe that it does download, but is unable to be imported into Radarr. It must be manually imported, even with Lenient Mapping.

**Expected behavior**
I expected the release to automatically be imported into Radarr after downloading the torrent file.

**Screenshots**
image
image
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Mono Version: 5.18.1.0 (tarball Fri Mar 15 20:45:47 UTC 2019)
 - Version: 0.2.0.1293

**Debug Logs**
Trace logs: https://pastebin.com/LdpGRgG8

[AB#879](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/879)

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
Support parsing of releases with 'AKA'

#### Todos
- [x] Tests
- [ ] Use parsed titles in matching

Fixes #3748

### CODE REVIEW

**Comment by bakerboy448** [comment]
Fixes https://github.com/Radarr/Radarr/issues/3748 ?

**Comment by qhello** [comment]
Any news on this? This would help a lot

**Comment by bakerboy448** [comment]
When an update is made either pushes will be made or comments will be made on the other issue.

you can also review the labels on this PR and the original issue as well.

**Comment by gitthangbaby** [comment]
never seen "AKA" but i see tons of titles simply mixing both titles, separated mostly by ".", "|", "-":
by popularity:
```
originaltitle YEAR LANG ..
regionaltitle YEAR LANG ..
originaltitle.regionaltitle YEAR LANG ..
originaltitle | regionaltitle YEAR LANG ,,
originaltitle-regionaltitle YEAR LANG ..
```
and except the first two, all fail with a message:

`    Failed to map movie, found title originaltitle regionaltitle, expected one of: originaltitle, regionaltitle.`

if you look at the message, it clears the separators and complains about something that's a clear match. It's just needs to be evaluated as correct imo.

**Comment by matijaerceg** [comment]
@gitthangbaby on PTP it is a very common practice to have 'AKA' in the filename of non-english movies

**Pull request merged**
