### PR TITLE
Media cover tweaks

### LINKED ISSUE #8006: Pull Sonarr commit 'Fixed: Images for some series not downloading'
Pull https://github.com/Sonarr/Sonarr/commit/b8481006932e904c93f46182ec4d91030d1461e1

```
git cherry-pick -ex b8481006932e904c93f46182ec4d91030d1461e1
```

This commit has 8 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#4746](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4746)

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
YES - 231

#### Description
Pull #8006, add excludeLocalCovers as query parameter to `/movies` endpoint

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* Fixes #8006

### CODE REVIEW

**Review by bakerboy448 — APPROVED** [review]
Lgtm

**Comment by bakerboy448** [comment]
prior to fixup; massive speed improvements for posterity

UI call: 25s and 55s
List Call: sub 1sec

```
2023-07-17 21:55:03.3|Trace|Http|Req: 26 [GET] /radarr/api/v3/movie (from 73.*.*.12 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-17 21:55:48.0|Trace|Http|Req: 77 [GET] /radarr/api/v3/movie?includeLocalCovers=False (from 127.0.0.1 Radarr/4.7.2.7657 (ubuntu 22.04))
2023-07-17 21:55:48.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-17 21:55:48.6|Trace|Http|Res: 77 [GET] /radarr/api/v3/movie?includeLocalCovers=False: 200.OK (590 ms)
2023-07-17 21:55:48.8|Trace|Http|Req: 78 [GET] /radarr/api/v3/movie?includeLocalCovers=False (from 127.0.0.1 Radarr/4.7.2.7657 (ubuntu 22.04))
2023-07-17 21:55:48.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-17 21:55:49.4|Trace|Http|Res: 78 [GET] /radarr/api/v3/movie?includeLocalCovers=False: 200.OK (594 ms)
2023-07-17 21:55:54.1|Trace|Scheduler|Pending Tasks: 0
2023-07-17 21:55:54.2|Trace|Http|Req: 79 [GET] /radarr/api/v3/movie?includeLocalCovers=False (from 127.0.0.1 Radarr/4.7.2.7657 (ubuntu 22.04))
2023-07-17 21:55:54.2|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-17 21:55:54.8|Trace|Http|Res: 79 [GET] /radarr/api/v3/movie?includeLocalCovers=False: 200.OK (625 ms)
2023-07-17 21:55:59.1|Trace|Http|Res: 73 [GET] /radarr/api/v3/movie: 200.OK (25131 ms)
2023-07-17 21:55:59.2|Trace|Http|Res: 26 [GET] /radarr/api/v3/movie: 200.OK (55865 ms)
```

**Comment by davidnewhall** [comment]
One request, if I may. Make the new input default `false`. I think it's `true` currently. False is easier to deal with when integrating the API. This request may mean renaming it to `excludeLocalCovers`. <3

**Comment by davidnewhall** [comment]
@mynameisbogdan I wasn't suggesting changing an existing value. This contribution isn't merged and appears to be adding a new boolean variable with a default of `true`. 

What is BC?

**Comment by bakerboy448** [comment]
if the default is true or the default is false as long as the param is named accordingly and as long as the default state is to return covers,  there's no BC impact right?

`excludeLocalCovers` default: False = Covers Included
`includeLocalCovers` default: True = Covers Included

no impact to prior users; only impacts the naming of the parameter and usage going forward.

**Comment by davidnewhall** [comment]
I'm not suggesting that we change the default output, that would break backward compatibility. 

I'm asking that we change the default value for this (and any new GET parameters) to `false`. As I stated originally, that may (likely) mean the parameter gets renamed to `excludeLocalCovers`, and the contribution goes through a small re-factor. 

Please ask questions if this doesn't make sense. I'm a professional, and there's no reason to treat me any other way.

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
228 stolen by Bogdan
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Datastore/Migration/228_add_bypass_to_delay_profile.cs

**Pull request merged**
