### PR TITLE
Fix for 7297. Add DVD-576p as a new Quality

### LINKED ISSUE #7297: DVD 576p releases treated being imported as Bluray-576p
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Grab a DVDRip release with PAL resolution (or larger than standard NTSC resolution) that is clearly tagged as "DVDRip" in the release name, Radarr looks at the file resolution and assumes it's Bluray-576p rather than at the release name.

### Expected Behavior

If a release is tagged as a DVDRip, this should trump quality assumptions made based on file resolution unless there is a big discrepancy (i.e., DVDRip-tagged release with 1920x1080 file resolution)

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

...
2022-05-16 17:19:14.6|Debug|VideoFileInfoReader|Getting media info from /media/movies/Movies (Radarr)/84C MoPic (1989) (imdb-tt0096744)/84.MoPic.1989.DVDRip.x264-HANDJOB.mkv
2022-05-16 17:19:14.6|Trace|AggregateLanguage|Considering Languages Unknown (Filename) from FileName
2022-05-16 17:19:14.6|Trace|AggregateLanguage|Considering Languages English (MediaInfo) from MediaInfo
2022-05-16 17:19:14.6|Debug|AggregateLanguage|Selected languages: English
2022-05-16 17:19:14.6|Trace|AggregateQuality|Considering Source DVD (Tag) Resolution 480 (Fallback) Revision v1 from FileName
2022-05-16 17:19:14.6|Trace|AugmentQualityFromMediaInfo|Resolution 694x568 considered 576p
2022-05-16 17:19:14.6|Trace|AggregateQuality|Considering Source UNKNOWN (Default) Resolution 576 (MediaInfo) Revision  from MediaInfo
2022-05-16 17:19:14.6|Trace|AggregateQuality|Selected Source DVD (Tag) Resolution 576 (MediaInfo) Revision v1
2022-05-16 17:19:14.6|Warn|QualityFinder|Unable to find exact quality for DVD,  576, and NONE. Using Bluray-576p as fallback
2022-05-16 17:19:14.6|Debug|AggregateQuality|Using quality: Bluray-576p v1
...

[AB#3165](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3165)

### PR DESCRIPTION
**Pull request by andy-reeves**
#### Database Migration
YES - XXXX | NO

#### Description
Adding DVD-576p as a new quality profile to support 576p DVD format.

#### Issues Fixed or Closed by this PR

* Fixes #7297

### CODE REVIEW

**Comment by Qstick** [comment]
Thanks for the contribution! Is this so common that we need a new quality for it? 

Pending that discussion, there are a few more things we need here should we decide to go ahead:

- Tests (Example releases that should be parsed to DVD 576p)
- Migration (we have to inject new qualities into existing profiles

**Comment by andy-reeves** [comment]
DVD-576p is the default for all Region 2 (European) DVD's produced.

**Comment by andy-reeves** [comment]
> Thanks for the contribution! Is this so common that we need a new quality for it?
> 
> Pending that discussion, there are a few more things we need here should we decide to go ahead:
> 
> * Tests (Example releases that should be parsed to DVD 576p)
> * Migration (we have to inject new qualities into existing profiles

I'll sort out a DVD-576p file we can use for testing. I'm not sure how to do the migration bit for existing profiles. I did a separate build that had a rename of 'DVD' quality to 'DVD-480p' but given how old that it I thought it best to leave 'DVD' to mean 'DVD-480p' and add 'DVD-576p' as the missing European quality.

**Comment by andy-reeves** [comment]
[Sample DVD576p file.zip](https://github.com/Radarr/Radarr/files/11304310/Sample.DVD576p.file.zip)

**Comment by Qstick** [comment]
Thanks, but what we really need are some example release names so that we can test the parser to make sure it's correctly identifying DVD 576p releases. 

There are a few examples you can go by for the migration from where we've added qualities in the past.

**Comment by andy-reeves** [comment]
Release names of European DVD's have only used 'DVD' in the past. The same issue exists with non-European DVDs with only 480 lines. They have all been released as 'DVD' and should have been [DVD480p.]

With the addition of this new quality profile then everything works as it does now; apart from local media files. If the local media files are [DVD] but 720x576 resolution (as are all Euro DVD's) then it will now correctly assign this as [DVD-576p] instead of [Bluray-576p]. Any links to the migration PR's so  I can prepare one of those please?

**Comment by Qstick** [comment]
If we can't identify from release names, then we'll have issues with a new quality. The release will get grabbed as one quality DVD and then the file will get identified with another, thus resulting in quality mismatches after download. Not ideal

I'd almost argue we should just fix the parser and map to the current DVD quality.

**Comment by andy-reeves** [comment]
Not sure you could fix it in the Parser. The current parser thinks a 720x576 resolution file has the best match with Bluray-576p quality. Currently, even if the file has [DVD] in the file name but a resolution of 720x576, it gets its quality set erroneously set to Buray-576p. What would you propose?

**Comment by Qstick** [comment]
Pushed a fix, let's see if that works before we take this further.

**Comment by andy-reeves** [comment]
Confirmed fixed in 4.5.1.7282

**Pull request closed without merging**
