### PR TITLE
New: Include renamed file information for Webhook and Custom Scripts

### LINKED ISSUE #5934: Pull Sonarr commit 'New: Include renamed file information for Webhook and Custom Scripts'
Pull https://github.com/Sonarr/Sonarr/commit/3c45349404f59064d1c8db0549401189c456e4c0

```
git cherry-pick -ex 3c45349404f59064d1c8db0549401189c456e4c0
```

This commit has 17 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#624](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/624)

### PR DESCRIPTION
**Pull request by junk-receiver**
#### Database Migration
NO

#### Description
This PR resolves #5934, and pulls in 3c45349404f59064d1c8db0549401189c456e4c0 from the upstream Sonarr repo. It implements the changes from the above commit, renaming Episode -> Movie as required in both class, variable, and file names.

The new JSON events have the following format:
```
{
  "movie": {
    "id": 1,
    "title": "Some Movie Title",
    "year": 2020,
    "releaseDate": "2020-01-01",
    "folderPath": "C:\\Movies\\Some Movie Title (2020)",
    "tmdbId": 0001,
    "imdbId": "tt0000001"
  },
  "renamedMovieFiles": [
    {
      "previousRelativePath": "Some.Movie.Title.2020.mkv",
      "previousPath": "C:\\Movies\\Some Movie Title (2020)\\Some.Movie.Title.2020.mkv",
      "id": 1,
      "relativePath": "Some Movie Title (2020).mkv",
      "quality": "Bluray-1080p",
      "qualityVersion": 1,
      "releaseGroup": "Release Group",
      "indexerFlags": "0",
      "size": 1
    }
  ],
  "eventType": "Rename"
}
```

While merging the above commit, I also discovered that the Discord Notification Provider had diverged from the upstream Sonarr version: the Radarr implementation was missing an implementation of the `OnMovieRenamed()` function. That function was modified in the above commit, so I went and implemented the Discord `OnMovieRenamed()` function to match the upstream implementation. If this was intentionally left out of the Radarr implementation, or if that should be split into another PR, please let me know and I'm happy to split it into another PR.

#### Testing
- All current tests in the test suite pass
- Manual verification that the new webhook is generated by renaming files in an small existing library and monitoring for POST events using a simple Python script
- Manual verification that the new Discord notification is generated successfully by renaming files in an small existing library and observing Discord notification messages in a private server

#### Screenshot (if UI related)
N/A, no UI changes.

#### Todos
- [ ] Tests
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #5934

### CODE REVIEW

**Comment by austinwbest** [comment]
Do we want to get in a scenario where a couple connects have different payloads than the rest when adding new things?

Seems it would be more consistent to add changes to all connects when making them. Maybe that is just me.

**Comment by junk-receiver** [comment]
I'm still fairly new to this codebase, sorry: I'm not sure I fully understand the question.

Are you referring to the fact that the `Webhook` connection now exposes more data for the "Rename" event than what other connections are able to?

**Comment by bakerboy448** [comment]
I believe he is.

In other words, why not update all notification endpoints and why update only a handful?

**Comment by austinwbest** [comment]
Yea.. Boxcar, email, etc.. All the other connects.

Otherwise when someone sees it available for one or two and then say but I want it too, now we have to go through and update them one by one or all the other at once after the fact. 

Seems like a wise choice to do it when added instead.

**Comment by junk-receiver** [comment]
I understand now, thanks for clarifying.

I definitely understand the desire for consistency between all the various Connection options.

Many of the current Connections don't support Rename events at all. I think it's out-of-scope for this PR for me to go and start adding new Rename events to new Connections that I've not used previously: can we file a new Issue to get all Connections to support the same set of events?

In terms of the current Connections that support Rename, we have:
- SynologyIndexer
- MediaBrowser
- Xbmc
- Slack
- Webhook
- PlexServer
- CustomScript
- Discord (support for Rename was added in this PR)

From what I can tell, most of these Connections don't actually have a way to consume the new payload, they just trigger an event (like a library re-scan) in response to any file getting renamed. These are:
- SynologyIndexer
- MediaBrowser
- Xbmc
- PlexServer

This just leaves the following connections which could actually consume the Payload and do something useful:
- Webhook (already updated in this PR)
- Slack
- CustomScript (already updated in this PR)
- Discord

If I was to update the Slack and Discord Connections to publish the new Payload data, that would bring all the Connections that currently support the "Rename" event up to parity with each other. Would that resolve your concerns with this PR?

**Comment by austinwbest** [comment]
Yea, that is all I mean. Just the ones that support it already :)

**Comment by junk-receiver** [comment]
@austinwbest sorry it took me so long! Is this sort-of what you had in mind? The Slack and Discord Connections now include information about which files were renamed for each Movie in an `OnMovieRename()` call.

The messages sent to Discord and Slack now have some text to them in addition to the Movie title. For each file renamed, there's an attachment describing which file was renamed in the format "<old filename> renamed to <new filename>". Since these are user-visible strings, I only used the filename / relativePath to keep it short and clean, but I can switch to a full-path version if you'd prefer.

**Review by Qstick — APPROVED** [review]
Code looks good, nice work

**Pull request merged**
