### PR TITLE
Fix regression for missing libgdiplus

### LINKED ISSUE #1065: After adding a movie, Radarr crashes
**Description:**
After adding a movie - via the Add Movies button, then typing in a movie title and clicking add - Radarr crashes and requires a restart.

**Radarr Version:**
0.2.0.480 - running on Qnap

**Logs:**
Nothing in the logs of note:
17-3-8 10:19:39.4|Info|MovieService|Adding Movie [][Madagascar] Path: [/share/Multimedia/Movies/Animation Library/Dreamworks/Madagascar (2005)]
17-3-8 10:19:39.8|Info|MediaCoverService|Downloading Poster for [][Madagascar] http://image.tmdb.org/t/p/original/2YiESGB68BGQSAFvfJxBi774sc4.jpg
17-3-8 10:19:39.9|Info|RefreshMovieService|Updating Info for Madagascar
17-3-8 10:19:40.9|Info|DiskScanService|Scanning disk for Madagascar
17-3-8 10:19:40.9|Info|MovieScannedHandler|[Madagascar] was recently added, performing post-add actions
17-3-8 10:19:41.0|Info|MediaCoverService|Downloading Poster for [tt0351283][Madagascar] http://image.tmdb.org/t/p/original/2YiESGB68BGQSAFvfJxBi774sc4.jpg
17-3-8 10:19:41.1|Info|MediaCoverService|Downloading Banner for [tt0351283][Madagascar] http://image.tmdb.org/t/p/original/wUetiqu2EFhHW94yTP0pWABfyUG.jpg

17-3-8 10:22:20.8|Info|Bootstrap|Starting Radarr - /share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.480
17-3-8 10:22:36.8|Info|MigrationLogger|*** Migrating data source=/share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-3-8 10:22:37.3|Info|MigrationLogger|*** Migrating data source=/share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-3-8 10:22:37.5|Info|Router|Application mode: Interactive
17-3-8 10:22:37.5|Info|OwinHostController|Listening on the following URLs:
17-3-8 10:22:37.5|Info|OwinHostController|  http://*:7878/
17-3-8 10:22:38.0|Info|NancyBootstrapper|Starting NzbDrone API

### PR DESCRIPTION
**Pull request by SWu**
Add back error handling for systems where libgdiplus is not available. Should fix #1065

#### Database Migration
No

#### Description
This function was moved but missed the exception handling for when the libgdiplus library doesn't exist on the system. Adding it back.

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* #1065

### CODE REVIEW

**Comment by onedr0p** [comment]
@galli-leo You might want to take a look at this.

**Comment by SWu** [comment]
Blah, I don't have a proper dev environment right now so I'm doing all this through github. How do I restart the errored build?

**Comment by onedr0p** [comment]
I'll restart it but appveyor has been acting up lately with failing builds that are passing.

**Comment by onedr0p** [comment]
Travis is failing due to a error on their end, and same with appveyor.

**Comment by SWu** [comment]
Closing this in favor of #1075 since this approach is getting too messy in my opinion.

**Comment by galli-leo** [comment]
This was fine. Can you please restore the branch?

**Comment by SWu** [comment]
See my comment in the other PR. I really didn't like this PR since it resulted in exposing GDI functionality in the DiskProvider interface, which is not really a disk operation anymore. Also it added extra exception throwing/catching/rethrowing for the ImageResizer which was also ugly.

**Comment by SWu** [comment]
Restored this branch. @galli-leo feel free to merge whichever version you want since you're the owner of this package, but I personally feel the other one is cleaner/more maintainable in the long run.

**Pull request merged**
