### PR TITLE
Updated Logos

### PR DESCRIPTION
**Pull request by flying-sausages**
#### Database Migration
NO

#### Description
Updated Logos

#### Screenshot (if UI related)
Please see changed files

#### Todos
- [x] Tests
- [x] Translation Keys
- [x] Wiki Updates

- [ ] Text logo rasters + vectors
- [ ] 4K logo

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by flying-sausages** [comment]
I'd _highly_ suggest using the outlined logos wherever possible as it won't look terrible against dark backgrounds like the one in prod does now

**Comment by reloxx13** [comment]
added
[ ] 4K Logo for 2 intances 🤪

**Comment by Qstick** [comment]
This would need quite a few more versions (favicons, app icons, etc..) that are sprinkled around the repo, and naming for the ones submitted needs to be identical to old.

**Comment by flying-sausages** [comment]
Heya, got my last deadlines on the 22nd, then I'm as free as a bird to work on this again

**Pull request closed without merging**
