### PR TITLE
Fixing Issue 840

### PR DESCRIPTION
**Pull request by scrouchman**
#### Database Migration
NO

#### Description
Adding an option to configure how frequently radarr queries download clients for finished downloads, defaulting to the current setting of once a minute

#### Todos
Code has no tests. I've based the logic off DownloadedMoviesScanInterval and I can't see tests for the usage of that either

#### Issues Fixed or Closed by this PR

* Issue-840

### CODE REVIEW

**Comment by scrouchman** [comment]
anything further I can do or this? Build is failing due to broken tests, but develop is failing as well.

**Comment by galli-leo** [comment]
@scrouchman No should be good, I will take a detailed look over the weekend. (I didn‘t have much free time the past few weeks).

**Comment by d1slact0r** [comment]
Would love this feature in the new build. 

Ref: https://github.com/Radarr/Radarr/issues/840

**Comment by jportny** [comment]
Hello, is this feature going to be released soon?  Thanks.

**Comment by scrouchman** [comment]
@galli-leo just chasing this up again

**Comment by fryfrog** [comment]
@scrouchman, have you considered talking to Sonarr developers to see if this is something they'd be interested in?

Also, what was your reason for making this configurable? It seems less useful to run it less frequently.

**Comment by scrouchman** [comment]
@fryfrog I don't use sonarr so I hadn't considered it, if there is a similar issue open and the codebase is similar I can easily port it.
On my setup deluge is constantly writing to disk even when paused so keeps the Nas awake. If I stop deluge then radarr logs an error every minute because it can't access it, which also keeps the Nas awake.
As it was already a requested feature and easy to do I thought I might as well add it. Its an advanced feature so shouldn't confuse those that don't need it

**Comment by M1kep** [comment]
@scrouchman Any idea what the build fail is? Also, what the chance of getting this in seconds? I personally would want to set this back to 30 seconds.

**Comment by scrouchman** [comment]
@M1kep As I did the work months ago it looks like the build error has been fixed. I've synced with develop and the tests pass now.
As for it being in seconds I can do that, but I went with minutes because the default is 1 minute and I didn't see the benefit in going lower than that. Reading the issue, its more for people that want a longer timeout than shorter one, so minutes made for a simpler UI for those that want the timeout in hours.

**Comment by galli-leo** [comment]
Sorry it took me so long to merge this, didn't find much time.

**Comment by tkdrob** [comment]
> @scrouchman, have you considered talking to Sonarr developers to see if this is something they'd be interested in?
> 
> Also, what was your reason for making this configurable? It seems less useful to run it less frequently.

https://github.com/Sonarr/Sonarr/pull/3127#issuecomment-493727496

**Pull request merged**
