### PR TITLE
New: Health Check for Downloads to Root Folder [common]

### PR DESCRIPTION
**Pull request by RobinDadswell**
#### Database Migration
NO

#### Description
Add a warning health check for downloading to a root path

#### Todos
- [x] Tests
- [x] Translation Keys
- [x] Wiki Updates

### CODE REVIEW

**Comment by RobinDadswell** [comment]
Tests to follow tomorrow

**Comment by bakerboy448** [comment]
[common] as well

**Comment by bakerboy448** [comment]
Robin validated with NZBget

I validated with SAB
`
Download client SABnzbd places downloads in /data/media/media/movies/, this is a root folder. You should not download to a root folder. `

functionality looks good

**Comment by RobinDadswell** [comment]
Still need to add the translation keys - however the reason I chose RemotePathMappingsCheck is because it already grabs back the DownloadClients and their folders and does checks based on those.

Let me know if you want that to change

**Comment by austinwbest** [comment]
> Still need to add the translation keys - however the reason I chose RemotePathMappingsCheck is because it already grabs back the DownloadClients and their folders and does checks based on those.
> 
> Let me know if you want that to change

Personally i dont think using that type is the right choice. It should be "DownloadingIntoRootFolderCheck" or something. For the notifications that dont remap the type and they see "RemotePathMappingsCheck " and ask support about it, 100% of the time the downloading into media folder wont be what is suggested to fix lol.. Not to mention it just makes sense to name the type based a little more on what it is doing.

**Comment by ta264** [comment]
I agree, I think they should be separate because they're checking different things.  Just make a new check that pulls in many of the same dependencies.  makes it much easier to follow in future IMO

**Comment by RobinDadswell** [comment]
Sounds good, I will update this evening

**Review by Qstick — APPROVED** [review]

**Pull request merged**
