### PR TITLE
Fixed: Handle missing category when getting Qbittorrent download path

### LINKED ISSUE #6993: Pull Readarr commit 'Fixed: Handle missing category when getting Qbittorrent download path'
Pull https://github.com/Readarr/Readarr/commit/6f97ca9a55471386454457ca52b93733e18e85e4

```
git cherry-pick -ex 6f97ca9a55471386454457ca52b93733e18e85e4
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#2498](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2498)

### PR DESCRIPTION
**Pull request by bakerboy448**
Fixes RADARR-7HC
Fixes RADARR-V49

(cherry picked from commit 6f97ca9a55471386454457ca52b93733e18e85e4)

#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Closes #6993

### CODE REVIEW

**Comment by Qstick** [comment]
Wrong sentry references for Radarr

**Comment by bakerboy448** [comment]
> Wrong sentry references for Radarr

Indeed - got some #s for me?

Also I assume this needs backporting to Sonarr as well?

**Comment by ta264** [comment]
RADARR-7HC
RADARR-V49

**Comment by bakerboy448** [comment]
> RADARR-7HC RADARR-V49

reworded and pushed

**Pull request merged**
