### PR TITLE
Fixed: Improve wording of add movie monitor dropdown

### PR DESCRIPTION
**Pull request by hugepants**
#### Database Migration
NO

#### Description
Change the wording of the `Monitor` dropdown options from the developer-friendly `True` and `False` to a more user-friendly `Yes` and `No`, this keeps consistency with Radarr v0.2.

#### Todos
- [ ] Tests
- [ ] Translation Keys

### CODE REVIEW

**Comment by austinwbest** [comment]
Changes related to UI text should be translated.

**Comment by hugepants** [comment]
It's not strictly UI text - it's dropdown text which is consistently in English across all Languages.

**Comment by bakerboy448** [comment]
sounds like the dropdowns should all be translated then...

**Comment by austinwbest** [comment]
> It's not strictly UI text - it's dropdown text which is consistently in English across all Languages.

I dont disagree with that :) but that is secondary to what my comment was. If changes are made related to language, they need to be adapted to use the language file & if they are not yet translated (such as yours) they need to be. You wont need to edit the json file as those words are already available & only need to be ran through the translate function :)

Hopefully that clarifies things

**Comment by Qstick** [comment]
Thanks for the PR @hugepants closing in lieu of #5319 and notes there to change to checkbox

**Pull request closed without merging**
