### PR TITLE
Optimized logo

### PR DESCRIPTION
**Pull request by ghost**
#### Database Migration
NO

#### Description
Optimized PNG's, reduced in size from 446kB to 147kB
Re-created the SVG with Inkscape, Inkscape was unable to render the SVG created with Sketch, this way everybody can open en use it.

### CODE REVIEW

**Comment by hotio** [comment]
Hold off a bit gonna take the honeycomb from Sonarr, stupid that I didn't think about this before

**Comment by hotio** [comment]
Hold off, I'm gonna use the honeycomb from Sonarr

**Review by ghost — APPROVED** [review]

**Comment by hotio** [comment]
Not quite perfect yet

**Comment by hotio** [comment]
Should be good now

**Review by ghost — APPROVED** [review]

**Pull request merged**
