### PR TITLE
Fix 4k detection

### LINKED ISSUE #5639: "4K" Releases are parsed as in the quality of 480p
**Describe the bug**
Releases with titles that contain "4K" are parsed as in the quality of 480p, causing unexpected rejection. 

**To Reproduce**
1. Execute a normal release search, either automatically or manually. 
2. "4K" releases are parsed as 480p. 

**Expected behavior**
"4K" releases should be parsed as in the quality of 2160p. 

**Screenshots**
image
The lower "WEB-DL 4K" release is parsed as WEBDL-480p, while the upper "WEB-DL 1080p" release is parsed correctly. 

**Platform Information (please complete the following information):**
 - Radarr Version 3.0.1.4259
 - Radarr Branch master

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
See GHI
#### Todos
- [X] Tests
- Translation Keys-N/A
-  Wiki Updates-N/A

#### Issues Fixed or Closed by this PR

* Fixes #5639

### CODE REVIEW

**Comment by tenshiak** [comment]
Some releases can be named with just "265" or "x265" so you don't want to limit it to h265.

**Comment by bakerboy448** [comment]
provide some real world examples please

**Comment by tenshiak** [comment]
Gladiator.2000.Extended.UHD.BluRay.2160p.DD.5.1.HDR.x265-RELEASEGROUP

Just changed the release group, it's from today.

**Comment by bakerboy448** [comment]
no need, appears existing logic handles fine 
image

**Comment by tkozybski** [comment]
Right it works in this case but i meant this part `(?:UHD|HEVC|BD|H265)|(?:UHD|HEVC|BD|H265)`
Better to not narrow it to just H265.

**Comment by bakerboy448** [comment]
rebased

**Comment by feellikealot** [comment]
@Qstick Can we get this reviewed please, this is blocking some workflows for couple of users. Thank you so much! :) Appreciate it!

**Comment by Qstick** [comment]
> @Qstick Can we get this reviewed please, this is blocking some workflows for couple of users. Thank you so much! :) Appreciate it!

@bakerboy448 says I shouldn't reward squeaky wheels....


JK we will get it checked and in when its squashed

**Comment by kgowru** [comment]
Hi! Can this be merged, my flow is currently blocked on this.

**Comment by wheelerlaw** [comment]
Does this resolve what #5639 was opened for? The following should be added as a test case:

```
Back to the Wharf 2020 WEB-DL 4K H265 10bit HDR DDP5.1 Atmos-PTerWEB
```

**Comment by bakerboy448** [comment]
@kgowru contrary to how companies work;  squeaky wheels do not get the grease.

@wheelerlaw if you look at either the commits for this PR the issue you referenced you'd see that this PR will fix/close that issue.
No additional test cases are needed; the ones their work.  And FWIW, you can test your case here using the regex from the commit. http://regexstorm.net/tester

you case works as expected

**Review by Qstick — APPROVED** [review]

**Comment by wheelerlaw** [comment]
> @kgowru contrary to how companies work; squeaky wheels do not get the grease.
> 
> @wheelerlaw if you look at either the commits for this PR the issue you referenced you'd see that this PR will fix/close that issue.
> No additional test cases are needed; the ones their work. And FWIW, you can test your case here using the regex from the commit. http://regexstorm.net/tester
> 
> you case works as expected

No it doesn't:

image

**Comment by bakerboy448** [comment]
@wheelerlaw it does
image

if it is still an issue in nightly after the next build that contains this fix (you'll see it on the update notes and it's building now) then fully fill out a bug report

**Comment by wheelerlaw** [comment]
@bakerboy448 Oh I see, I forgot to tick of the "Ignore case" box. Thanks!

**Comment by kgowru** [comment]
> @kgowru contrary to how companies work; squeaky wheels do not get the grease.
> 
> @wheelerlaw if you look at either the commits for this PR the issue you referenced you'd see that this PR will fix/close that issue.
> No additional test cases are needed; the ones their work. And FWIW, you can test your case here using the regex from the commit. http://regexstorm.net/tester
> 
> you case works as expected

Appreciate this @bakerboy448 🙏

**Pull request merged**
