### PR TITLE
Fixed: XSS vulnerability in the navbar search.

### PR DESCRIPTION
**Pull request by ScottBurfieldMills**
#### Database Migration
NO

#### Description
The code to generate the empty template for typeahead search results was concatenating the unsanitized query into the template HTML, making it possible to add malicious JavaScript code.

#### Issues Fixed or Closed by this PR

* #2503

### CODE REVIEW

**Comment by galli-leo** [comment]
Am I correct, that this isn't really an issue? Since you need to type in the search box for it to happen, you could only do it to yourself right? Because else this would necessitate a release.

**Comment by ScottBurfieldMills** [comment]
I think you could only do it to yourself or to someone else's instance of Radarr if you already had their username and password.

@rog0rr any thoughts?

**Comment by attritionorg** [comment]
If the request can be done via GET, where the XSS code is passed as an argument, it would be a reflected XSS attack and a valid issue. Trick a user into clicking on the link, they would potentially disclose credentials etc. If it truly requires you to type it in the search field, then it is a 'self hack' and does not cross privilege boundaries, and not a vulnerability.

**Comment by ScottBurfieldMills** [comment]
The navbar search seems to only search a JS array of movies in your library already, so this is a 'self hack' and wouldn't really be an issue or require a release.

**Pull request merged**
