### PR TITLE
Added: Radarr now stores cookies for PTP beyond restarts. 

### PR DESCRIPTION
**Pull request by galli-leo**
Should limit active PTP sessions correctly.

#### Database Migration
YES

#### Description
Currently, if a user forces a log out via PTP or the cookies become invalid in another way, we wont recover.

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* #2626

### CODE REVIEW

**Comment by galli-leo** [comment]
@Qstick Could you review this and maybe provide some feedback on how we might recover, if the cookies become invalide due to e.g. PTP removing sessions?

**Comment by Qstick** [comment]
Sure, will do

**Comment by galli-leo** [comment]
@Qstick And maybe comment on, if you find the current way I store cookies to be too hacky (With the func and action properties).

**Comment by Qstick** [comment]
Ok will do, I’m going to try and find some time this afternoon or evening to test it and go thru code closely.

**Comment by galli-leo** [comment]
No need to rush, the current code works fineish

**Comment by Qstick** [comment]
Do stored cookies also need to be used for dl requests with PTP or no?

**Comment by galli-leo** [comment]
No idea. Iirc no, since the torrent url is unique? I will have to try that.

**Comment by Qstick** [comment]
I think we had that issue with gazelle is why I ask. I think the func/action method works I was trying to think of something that might work cleaner so that it's handled in the base class instead of each indexer, but couldn't come up with anything last night. Seems to work.

**Comment by galli-leo** [comment]
@Qstick Well it's mostly already handled in the base class. While we could probably handle getting and setting the cookie inside fetch indexer response, we would still need something per indexer, for the auth call (if the cookie is invalid). So IMO this is probably the best solution for now. (Also IIRC, the http client does some cookie storing for an hour anyways, so downloading a torrent shouldn't be a problem. You make a correct indexer call with cookies, http client stores those, when downloading the torrent those cookies are provided by the http client. The only reason this wouldn't work correctly, is probably if the download url has a different domain name, e.g. download.ptp.me)

**Comment by Qstick** [comment]
@galli-leo ok, I think it looks good then. I think you are right about the 1 hour cache in HttpClient. Appveyor seems to be failing for some reason during windows exe creation and there is a conflict with .idea files.

**Comment by galli-leo** [comment]
Yeah the installer exe script doesnt like branches with / in them, since it thinks it’s a dir separator.

**Pull request merged**
