### PR TITLE
Fix #1352 - 'nordic' matches all of the nordic languages

### LINKED ISSUE #1352: English is wanted, but found Norwegian/Danish
There should be possible to add several languages in the profile settings.  Or is there a way to get around this? Because the torrent says NORDIC or DanishBits radarr thinks the language is Norwegian or Danish but it's just the subs. 
http://imgur.com/jo2nBw6
http://imgur.com/a/CVzzX

**Radarr Version:**
0.2.0.596

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

### PR DESCRIPTION
**Pull request by everlof**
#### Database Migration
NO

#### Description
It seems like the definition of "nordic" is wrong - it should be identified as all the Nordic languages.

#### Todos
- There didn't seem to be any tests for this.. Found a  "// TODO Add tests for this in the title-parser.."

#### Issues Fixed or Closed by this PR

* #1352
* #3466

### CODE REVIEW

**Comment by Qstick** [comment]
Language tests added back in https://github.com/Radarr/Radarr/commit/6706138fa0f9a5a351a58c2a84cbc298579312b0. You should be able to add a test case in the LanguageParserFixture.cs

**Comment by everlof** [comment]
How do I run the test suite? Is that included in `build.sh`? I get errors when I run `test.sh` like:

```
$ ./_tests/netcoreapp3.1/osx-x64/publish/test.sh Mac Unit Test
The test source file "/Users/davideverlof/repo/Radarr/./_tests/Radarr.Api.Test.dll" provided was not found.
```

**Comment by everlof** [comment]
@Qstick I've added a unit-test for nordic now! Worked great.

**Comment by Qstick** [comment]
I don't think this solves or fixes 1352. That issues seems to point out that `nordic` in the release usually just means nor/dan/etc.. subs not audio, however Radarr is taking it to be the main audio language and assigning Norwegian. In reality it should be English. The other issue #3466 also eludes to the fact that the ideal solution would be `nordic` not being recognized at all... So I'm not sure this is the right fix.

**Comment by everlof** [comment]
Okay, maybe I should create a new issue?

Any 1:1 mapping between Nordic and Norwegian should be wrong in my opinion.

I’ve had downloads not started because it considered “Nordic” as
“Norwegian”, and my profile asked for “Swedish. That’s what I set out to
solve, and that’s what I thought those issues was trying to solve as well.


sön 5 juli 2020 kl. 07:39 skrev Qstick <notifications@github.com>:

**Comment by Qstick** [comment]
No new issue needed. Yes the 1:1 mapping between Nordic and Norwegian is wrong. If you read the issues they are advocating for English or default language, `nordic` shouldn't receive special treatment as it usually just means subs.

**Comment by Qstick** [comment]
Closed with 3a0aa51cbf497e14f31da387405145ecaf9363e9

**Pull request closed without merging**
