### PR TITLE
Fix false positive on remotepathhealthcheck for downloadstation client 

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Todos
- [*] Tests

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by margaale** [comment]
Ha, never thought that anyone else would dare to read my code...

**Comment by margaale** [comment]
@ta264 i did the changes...

**Comment by margaale** [comment]
Did the squash and a rebase. I don't know what is failing or if its related to the commit...

**Comment by Qstick** [comment]
> Did the squash and a rebase. I don't know what is failing or if its related to the commit...

Ignore, just azure being stupid

**Pull request merged**
