### PR TITLE
Added Czech language

### PR DESCRIPTION
**Pull request by halali**
#### Database Migration
NO

#### Description
Followed the Hebrew language, added a test

#### Todos
- [x ] Tests
Added TestCase for Czech language parsing

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by galli-leo** [comment]
Why did you delete the iso language?

**Comment by halali** [comment]
Becouse in Tracker are titles in english lang and witch czech iso it was not able to find any release.

**Comment by halali** [comment]
ISO Lang is now good when alt titles work

**Comment by onedr0p** [comment]
I wouldn't delete Hebrew language ISO, try to find a way to work with it..

**Pull request closed without merging**
