### PR TITLE
[http://feathub.com/Radarr/Radarr/+42]Remove movie once the movie folder is removed

### PR DESCRIPTION
**Pull request by Rusk85**
As the OP suggested in F+42:
>My suggested behavior is that if you remove the file itself, you are actually indicating that you want to keep the movie in the list (most likely to redownload it) and when you delete the whole folder you want to remove the movie from the list because you are one with it.

#### Database Migration
NO

#### Description
For now I have added that movies, that have been manually deleted from disk without their parent folders gone, will be marked as monitored again as opposed how it is handled now. Now manually deleted movies from disk whose parent folder still exists, will be left in the library but won't be set to unmonitored.

#### Todos
- [ ] Tests (can't run all tests locally so I decided to PR half-way into the feature)
- [ ] Setting correct monitoring state for movies that have been **manually deleted from disk** with their parent folder remaining depending on the setting `Ignore Deleted Movies`
- [ ] Handling **manually from disk deleted** movies as well as their parent folders correctly, so that the user has control over what happens by way of a UI control (movie is deleted from library, movie folder is recreated and movie set to monitored, movie folder is created and movie set to unmonitored)
- [ ] In all cases check if some form of housekeeping is necessary such as deleting folders with empty or irrelevant content
#### Issues Fixed or Closed by this PR
* [+42](http://feathub.com/Radarr/Radarr/+42) Intended to add feature F+42 as described [here](http://feathub.com/Radarr/Radarr/+42) by OP and specified [here](https://goo.gl/DzO37N) in more detail

### CODE REVIEW

**Comment by fryfrog** [comment]
What if the user has the movie, but it is marked `unmonitored`, then deletes the file? Will it get monitored even though it was previously unmonitored? Shouldn't it be more like the file being deleted doesn't result in a monitor/unmonitor change at all? And deleting the folder *and* movie should remove it from Radarr entirely? (even though Sonarr *doesn't* act like this?)

**Comment by galli-leo** [comment]
I would highly suggest making this optional. I also think you have to check the settings, since there's an option to unmonitor the movie, once it gets deleted. Maybe add a dropdown selection?: On folder deletion: Don't change, Unmonitor, monitor, delete movie and the same for on file deletion.

**Comment by galli-leo** [comment]
Also please ignore the appveyor tests, they just randomly fail sometimes.

**Comment by Rusk85** [comment]
First of thanks for the great advice. 

@fryfrog I am really just trying to realize the Feature Request as it was set out:
> [My suggested behavior is that if you remove the file itself, you are actually indicating that you want to keep the movie in the list (most likely to redownload it) and when you delete the whole folder you want to remove the movie from the list because you are one with it.](http://feathub.com/Radarr/Radarr/+42)

Considering this a user story lets break it town to a few tasks:

- Deleting a movie file w/o it's parent folder **manually from disk**, leaves the monitoring status of the movie untouched. For example: movie file is deleted and movie was monitored before removal, will make it monitored again ( @fryfrog thanks for pointing out that logic inconsitency there)
- Deleting a movie along with it's parent folder **manually from disk**, removes the movie from radarr's library entirely

@galli-leo Could you elaborate on a few things your said:
1. > I would highly suggest making this optional.
2. > Maybe add a dropdown selection?: On folder deletion: Don't change, Unmonitor, monitor, delete movie and the same for on file deletion.
 
Especially the 2nd point I am not really understanding. That way you would take a pretty simple convention and blow it out of proportion by having to set this for every movie possibly at a point in time where you are unable to make an informed decision.

**Comment by galli-leo** [comment]
@Rusk85 Sorry I meant a global option like we currently have (Settings -> Media Management -> Ignore Deleted Movies)

>As a quick addendum current behaviour is as such:
>
>- Deleting movie file w/o parent folder => movie is set to unmonitored regardless of its previous monitoring state
>- Deleting movie file along with its parent folder => movie is set to unmonitored and its parent folder is recreated

This is only the case if aforementioned option is disabled. I just wanted to make sure that this existing functionality is not broken for users and hence the options mentioned above.

**Comment by Rusk85** [comment]
@galli-leo Ah now I *think* I understand. Just found the option as well which was turned on while I was hacking away at that feature. That would mean that the first part of the feature might very well be already implemented. Will have to check though.
And you propose another checkbox/frontend control for deleted movies along with their parent directory such as that either 1. the movie is being remonitored and its parent folder recreated
2. the movie is being unmonitored and its parent folder recreated
3. the movie is removed from the library

Did I get that right? 

Have to add thought that I am **slowly** getting the hang of how the internals of the backend work, but I am utterly clueless when it comes to adding frontend controls and wiring them up with the backend. Some pointers/examples would be great.

**Comment by fryfrog** [comment]
Behaviors and options:

File Removed:
* Unchanged - Obvious, don't do anything. Don't remove from Radarr, don't change monitor status, should still obey empty folder setting.
* Unmonitor - Just like the existing option, leave in Radarr but unmonitors. Great for use case of watching a movie and then deleting it. *Should* probably follow the empty folder setting. Deletes folder or not based on that.
* Monitor - New behavior, use case would be person who deletes files that are found to be bad and wants them automagically replaced.

Directory Removed:
Same as above.

**Comment by LSL1337** [comment]
any update on this feature? It still doesn't work for me. If I delete a movie in Plex, it will not be unmonitored in Radarr, so sometimes Rss Sync downloads it again.
Ignore Deleted Movies is set to Yes.

any ideas?

**Comment by scope999** [comment]
This is also not working for me. If I delete a movie in plex or from windows file system the movie consistently remains monitiored in radarr and is downloaded again. Ignore deleted movies is set to yes for me too.

**Comment by theCheek** [comment]
I'm a little confused on this one. I have a script which deletes movies that the oldest movie in the media folder to make room for new downloads. I would like Radarr to remove this movie completely from its list. At present the script just removes the movie file, which is resulting in Radarr marking the movie as unmonitored.

I agree that if the parent folder is deleted, this should indicate that the user no longer wants the movie in his/her list, and should remove it completely. However when I have tried modifying my script to remove the parent folder, no change seems to take place. 

Note: 'Ignore Deleted Movies' is set to 'Yes'.

**Comment by theCheek** [comment]
@galli-leo is there any chance of merging this into the base branch if its working as intended?

By intended I mean the OP suggestion -  deleting the file sets it to unmonitored, but deleting the parent folder removes it from radarr altogether.

**Comment by lunzet** [comment]
will this feature still be developed somewhere in the future?

**Pull request closed without merging**
