### PR TITLE
Add Synology Download Station

### PR DESCRIPTION
**Pull request by onedr0p**
#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* #715

### CODE REVIEW

**Comment by margaale** [comment]
You might want to wait a llitle for Sonarr/Sonarr@ #1672

**Comment by onedr0p** [comment]
Let me know when it's complete on Sonarr and I'll merge the rest of the changes.

**Comment by margaale** [comment]
Merged

**Comment by margaale** [comment]
Don't hesitate to contact me if you need help with any bug regarding this feature... 
Good luck

**Comment by onedr0p** [comment]
I merged it in, but I cannot test, let us know if you run into any problems.

**Comment by margaale** [comment]
Actually I'm the one who developed this for sonarr...

**Comment by onedr0p** [comment]
Ok then, feel free to submit a PR if anything arises.

**Comment by oliroe** [comment]
Hi. Tried using this but getting an error that access to the path is denied

> DownloadMonitoringService	Couldn't process tracked download Saving.Private.Ryan.1998.iNTERNAL.1080p.BluRay.H264.AAC-RARBG: Access to the path "/volume1/Download Station/Saving.Private.Ryan.1998.iNTERNAL.1080p.BluRay.H264.AAC-RARBG" is denied.

**Comment by margaale** [comment]
Is that the right path? does it exists?

**Comment by oliroe** [comment]
Yep, definitely right. It's the default path used by Download Station and not my own. The files download to there but then the renamer doesn't work to move it

**Comment by margaale** [comment]
Don't know much about raddar, i'm using sonarr in my house and i had never seen that error before. Maybe some dev around here can throw some light into it.

**Comment by oliroe** [comment]
Ok. Do you know what the format of the file path should be when you setup the download client? Tried to test a different path than the one used by Download Station but I get errors when using both /volume1/ and volume1/

**Comment by margaale** [comment]
Neither. Are you using category or directory? Where are you running radarr?

**Comment by oliroe** [comment]
Was just going to use Directory and try a different folder from the one used by Download Station to see if that worked. Will try changing the category to see if that makes a difference

**Comment by margaale** [comment]
If you use directory it should be the shared folder path (video/movies for example) and then you will have to setup remote path that points to the physical path (/volume1/video/movies)

**Comment by oliroe** [comment]
Definitely not working for me and have gone back to using Transmission. Will try again another night. If anyone else successfully used this could you post your settings here for me to test.

Thanks

**Comment by onedr0p** [comment]
@margaale would you mind testing this to make sure it works? I can't because I don't own a nas.

**Comment by margaale** [comment]
@oliroe when do you get that error? I've just started downloading a movie with no problem.

**Comment by oliroe** [comment]
Hi. I only get the error when Radarr tries to rename and move the file.
That's when it says access to the folder is denied

**Comment by oliroe** [comment]
@margaale Did it successfully move the file in your setup?

**Comment by margaale** [comment]
Was downloading when i left. What option should i enable? Something like
handle completed - remove? O something else? Remember i'm not a radarr user.

**Comment by oliroe** [comment]
Apologies. In Settings go to Media Management and select Rename Movies

**Comment by margaale** [comment]
Hi, it's working here. 

1. Go to download clients, add download station and under category writeradarr (this folder should exists on your syno)
2. After adding the client, go to Remote Path Mappings(i'm using windows to run this). Should look something like this:
a) Syno IP -> /volume1/video/Sin Clasificar/radarr/ -> \\DISKSTATION\video\Sin Clasificar\radarr\
b) Syno IP -> /volume1/video/Peliculas/ -> \\DISKSTATION\video\Peliculas

Maybe with only /volume1/video -> \\DISKSTATION\video should be enough, but i don't use sonarr that much either to know for sure.

And that's it. The movie got renamed and moved, also intermediate files were removed too.

**Comment by oliroe** [comment]
Hi

Appreciate your reply. Tried a few combinations but still get the access
denied error. Shouldn't have to use the remote mapping when Radarr and
Download Station are on the same NAS.

**Comment by margaale** [comment]
That's correct. Let me ask you how do you run this   development version of radarr

**Comment by margaale** [comment]
That's correct. Let me ask you how do you run this development version of radarr  on your syno. I wanna try out myself...

**Comment by oliroe** [comment]
I just installed the spk from synocommunity and changed the version from
develop to nightly within settings in Radarr. Working really well so far
bar this issue

**Comment by oliroe** [comment]
Changing the destination directory when setting up the download client also fails. It passes the test when saving the client but any torrent that tries to start fails with the error below

Have tried using the format \DISKSTATION\ or /volume1/

> NzbDroneErrorPipeline	Request Failed: Failed to add torrent from url magnet:?xt=urn:btih:43054fc0fa7f530d0b6575e6ff8c2239adedb09a&dn=Toy.Story.2.1999.1080p.BRrip.x264&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce. Reason: Destination does not exist

**Comment by margaale** [comment]
You are not getting that it should be the shared folder name there, not the
physical. Try  leaving both empty and tell me what happens

**Comment by oliroe** [comment]
Hi. Only trying to change the folder to get around my initial problem. Leaving it blank downloads the torrent but fails on moving with this error

> DownloadMonitoringService	Couldn't process tracked download Saving.Private.Ryan.1998.iNTERNAL.1080p.BluRay.H264.AAC-RARBG: Access to the path "/volume1/Download Station/Saving.Private.Ryan.1998.iNTERNAL.1080p.BluRay.H264.AAC-RARBG" is denied.

Because of this I'm trying to change the download folder from the default in download station. Putting a folder address in the directory when setting the download client produces this error when trying to start the download

> NzbDroneErrorPipeline Request Failed: Failed to add torrent from url
 magnet:?xt=urn:btih:43054fc0fa7f530d0b6575e6ff8c2239adedb09a&dn=Toy.Story.2.1999.1080p.BRrip.x264&tr=http%3A%2F%
 2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me
 %3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce.
 Reason: Destination does not exist

**Comment by margaale** [comment]
Sorry man. Cannot help you from here I even offered to configure it myself.
Not have the time to write a tutorial, so if anyone gets it to work please
write one to help others. All I can tell you is that is working fine on my
setup and others are using it at sonarr with no issues. So  I'm guessing it
must be a configuration/permission problem on your side...

**Comment by oliroe** [comment]
Really appreciate your help here. I'll continue to play around with it and will update if I find a solution. I'll also look out to see if there are any other Radarr users who are having problems.

Thanks again

**Comment by margaale** [comment]
@oliroe see #1686

**Comment by oliroe** [comment]
Thanks for that. Out of interest I installed Donate and had the exact same issue for me as Radarr. It's strange because I've had SickBeard, Sickrage, Couch potato and Headphones installed on this NAS and they've all worked with Download Station. Will keep trying and report back if I find a solution

**Comment by margaale** [comment]
I still believe its a permission/configuration issue. Try that branch, it will tell you at least if the directory exists, if you are willing to test i think i can get the actual permissions and log them in debug level...

**Comment by margaale** [comment]
Under what user runs radarr?

**Comment by oliroe** [comment]
Willing to try anything and appreciate the help. Radarr installed as admin
which I use for all installs

**Pull request merged**
