### PR TITLE
Initial support to Brazilian Portuguese (pt-br)

### PR DESCRIPTION
**Pull request by dyorgio**
#### Database Migration
NO

#### Description
Included pt-br codes and adjust IsoLanguage.Find to work with any lenght code

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* #1626

### CODE REVIEW

**Comment by Qstick** [comment]
Likely won't add this to develop, you can PR against Aphrodite

**Comment by dyorgio** [comment]
@Qstick is it ok now? or I need to checkout and modify Aphrodite branch and make a new PR?

**Comment by Qstick** [comment]
You'll likely need to redo it, things have moved a bit with languages

**Comment by alpe12** [comment]
Can anyone try this again, please?

**Comment by dyorgio** [comment]
done guys, new PR here: https://github.com/Radarr/Radarr/pull/3877

**Pull request closed without merging**
