### PR TITLE
Added: AHD_Gold and G_DXVA indexer flags

### PR DESCRIPTION
**Pull request by nyanloutre**
#### Database Migration
NO

#### Description
Add AHD specific flags that can be used in custom formats

### CODE REVIEW

**Comment by nyanloutre** [comment]
This PR is still relevant

**Comment by Qstick** [comment]
We are mostly just doing fixes to develop branch, feel free to move this to Aphrodite and we can get it merged in

**Comment by Qstick** [comment]
Seems you changed to Aphrodite and then changed back?

**Comment by nyanloutre** [comment]
@Qstick yes I need to make some changes to my commits but didn't take the time yet

**Pull request closed without merging**
