### PR TITLE
Cleanup Series Code

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
YES

DB Migration to Remove Series related Tables and Columns

#### Description

This removes all tv related code from the Core project and Core.Test project. Tests have been made build able, but need a lot of work to get in shape.

- Cleanup Blacklist Service and Repository
- Cleanup DecisionEngine
- Cleanup DownloadDecision
- Fix DiskSpaceService to calculate freespace with Movie paths instead of Series paths.
- Cleanup PendingRelease Service and Repo
- Cleanup Tracked Download Service
- Cleanup Download Clients
- Cleanup Housekeepers
- Clean Indexers
- Clean Indexer Search Criteria
- Cleanup ModiaCovers
- Handle MovieDeletedEvent in MediaCoverService so that image cache gets removed when movie is removed from library.
- Cleanup HealthChecks
- Fix RootFolder HealthCheck to look at Movies instead of Series
- Cleanup MediaFiles
- Cleanup Parser

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by Qstick** [comment]
Appveyor failing seems to be unrelated cake issue.

**Comment by galli-leo** [comment]
So the only todos are the tests?

**Comment by Qstick** [comment]
Yes for the most part, let me go back through everything and double check

**Comment by galli-leo** [comment]
Sounds good, just waiting on the npm fix, so this actually builds.

**Comment by Qstick** [comment]
I think we should be OK now. Main to do is the tests, However would be good to have this on nightly for a bit before you do another release just in case there are any small bugs that pop up.

**Comment by galli-leo** [comment]
Yeah, I am thinking of doing a hotfix release due to the mono 5.10 issues, without this fix forst

**Comment by Qstick** [comment]
Rebased

**Comment by galli-leo** [comment]
@Qstick Sorry can you rebase again? Forgot to merge it again :/

**Comment by Qstick** [comment]
No prob

**Comment by Qstick** [comment]
Rebased

**Pull request merged**
