### PR TITLE
New: Quality Preferred Setting

### LINKED ISSUE #3659: File size - I want the biggest.
Hi. Is it possible to have Radarr choose the biggest file available at the desired quality?
Modifying the file size sliders for a given quality is not a solution. Some 1080p blu ray rips are tiny if they are old movies which have been up scaled or whatever. Newer movies with all of the fancy audio tracks, HDR and all that stuff are enormous. I just want the best available, which is the biggest file 99% of the time.

Seen this mentioned a few times. Some say it should already do this and its a bug if it doesnt. Other places say to adjust the minimum size sliders. But I already said why that isn't a solution.

Cheers,
Chris

### LINKED ISSUE #4118: Preferred Quailty Size Setting
**Is your feature request related to a problem? Please describe.**
Right now there is a minimum/maximum size limit per quality type and no way to specify a preferred size.

**Describe the solution you'd like**
It would be beneficial to have a preferred size setting, this would allow you to have a much larger range for quality size limit (min/max), but then having a preference for a particular size would enable you to more control of the releases picked. It could also allow upgrades from larger sized release to a release that is closer to your preferred size within the same quality type.

I've included a mock up picture that was provided by Qstick for reference.

**Describe alternatives you've considered**
Custom formats to control release sizes, but this does not work well because it cannot be controlled dynamically based on video length...

**Additional context**

unknown

Edit, I looked to see if there was an open issue for this, but did not find one, sorry in advance if this is a duplicate...

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
YES (171 PreferredSize Column to Quality Definitions)

#### Description
Adds third slider to quality definitions, prioritize downloads based on closest to preferred size. This allows user to spec if they want smallest, largest, or someone in between for a given quality

image

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR
Fixes #4118 
Fixes #3659 ? I thought it already worked like this...

### CODE REVIEW

**Comment by UnknownUser6** [comment]
I like the feature very much, although I would like it to redownload a file if it is closer to the preferd size while having the same quality. Lets say it downloaded a 9 gb file while my prefered size would be 5 gb. As soon as there is a file closer to 5 gb it should replace it with that.

**Comment by ItsME6969** [comment]
Was this abandoned? Implementing this would greatly reduce my use of preferred words and increase the chances of getting the desired qualities and size range.

**Comment by ta264** [comment]
No, it's been in Radarr since April 2020

**Comment by ItsME6969** [comment]
> No, it's been in Radarr since April 2020

Oh yea I know my bad, I went from the Sonarr thread to this one and I thought I was still on the Sonarr GitHub. It's such a powerful feature and is the only thing I think is missing in Sonarr. And looks like there was some talk about it but somehow never came to fruition.
https://github.com/Sonarr/Sonarr/issues/724

**Pull request merged**
