### PR TITLE
Rename Sonarr to Radarr

### PR DESCRIPTION
**Pull request by morberg**
#### Database Migration
NO

#### Description
Rename Sonarr to Radarr

#### Todos
None

### CODE REVIEW

**Comment by morberg** [comment]
I update this manually on my machine after each new release of Radarr. Seems this change will break the automated tests. I don't have that environment up and running, should I submit an issue instead and let someone else do the renaming?

**Comment by galli-leo** [comment]
Yeah. Can you update the build scripts (appveyor-build.cake as well as build.sh and package.sh) for the osx part (Just search for Sonarr & replace with Radarr)? Then I can merge the change.

**Comment by morberg** [comment]
Sure thing.

`package.sh` seemed unrelated to my original commit (?), but I get why you want that changed as well.

**Comment by galli-leo** [comment]
Can you change CFBundleExecutable inside Radarr.app/Contents/Info.plist to Radarr as well? Else the mac app won't launch.

**Comment by morberg** [comment]
Absolutely.

**Comment by galli-leo** [comment]
Cool thank you very much for this. Seems to be working great now!

**Pull request merged**
