### PR TITLE
Add linux-x86 support

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

#### Description
Add support for 32bit linux

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by Qstick** [comment]
Update server needs updated to support these, I'm not sure the release parsing regex will pick it up. 

```
        public static readonly Regex LinuxAsset = new Regex(@"linux(-core-(x64|arm|arm64))?\.tar.gz$", RegexOptions.Compiled);
```

**Comment by Qstick** [comment]
Also, size difference is pretty major, assuming no issues there. The win x86 and x64 packages are around 10mb apart.

image

**Comment by Qstick** [comment]
> Update server needs updated to support these, I'm not sure the release parsing regex will pick it up.
> 
> ```
>         public static readonly Regex LinuxAsset = new Regex(@"linux(-core-(x64|arm|arm64))?\.tar.gz$", RegexOptions.Compiled);
> ```

https://github.com/Servarr/ServarrAPI.Update/commit/217d9ba4d7462443add45787ea79a5d705ade853

**Comment by ta264** [comment]
> Also, size difference is pretty major, assuming no issues there. The win x86 and x64 packages are around 10mb apart.
> 
> image

Digging around a bit I believe this is because the `linux-x86` framework components haven't been run through `crossgen2` to turn them into native machine code, since it's a cross-built SDK and not a native built one, unlike the official `linux-x64` SDK.  This is the same as for `freebsd-x64` and the filesizes are very similar to the freebsd build.

Given that, and that the tests all pass, I don't think we need to worry.  But good spot!

**Review by Qstick — APPROVED** [review]

**Pull request merged**
