### PR TITLE
Extra data

### PR DESCRIPTION
**Pull request by fhscholl**
#### Database Migration
**YES**

#### Description
Enable parsing and importing of most extra files. Does not currently handle metadata files.

This includes cherry picked changes from Sonarr to ignore case and add language to subtitle file names.

In addition this includes a parser definition for "forced" subtitles

Updated tests.

#### Todos
- [X] Tests

#### Issues Fixed or Closed by this PR

* #2214 (partial)
* #121

### CODE REVIEW

**Comment by galli-leo** [comment]
Have you implemented moving the files when renaming the folder?

**Comment by fhscholl** [comment]
I didn't test that. I will later

**Comment by OoGuru** [comment]
Oh this is very nice to see. I had just run into some trouble with renaming have started to work on a post processing script, but this looks promising. Have you had any chance to look into @galli-leo 's suggestion @fhscholl ?

**Comment by galli-leo** [comment]
@fhscholl Did you have time to test that?

**Pull request closed without merging**
