### PR TITLE
Update InteractiveSearchRow.js

### PR DESCRIPTION
**Pull request by davidjmorin**
#### Database Migration
No

#### Todos
- [ ] Tests
- [ ] Translation Keys
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

Added moving tooltip to right of icon instead of bottom

### CODE REVIEW

**Comment by RobinDadswell** [comment]
What's the issue with it being underneath at the moment?

**Comment by davidjmorin** [comment]
> What's the issue with it being underneath at the moment?

I find it gets in the way if you accidently hover over it.  Kind of a pain.  I tested with a custom CSS and moving it to the right is 100% better.

**Comment by imwireless** [comment]
I have to agree with this.  It does get in the way although just moving your mouse all the way to the right will git rid of it.

**Review by imwireless — APPROVED** [review]
I like the idea.

**Comment by RobinDadswell** [comment]
Currently leaving as it is, there are plans in V4 to change the interactive search interface.

**Pull request closed without merging**
