### PR TITLE
Fixed: Rare timing issue on first-use causing duplicate naming config

### LINKED ISSUE #2773: Can't access settings
So this issue is identical to #2039 , only the solutions there have not worked for me.
I am on Pre-Release v0.2.0.1067. I am a first time user of radarr, but have used/am using sonarr.
I am on windows 7, and i have imported my movie library, but when i went to setup the settings for my indexer and media management settings, the 4 dots move back and forth endlessly.

I get this error 18-5-12 11:34:05.1|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.1067] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Datastore.BasicRepository`1.SingleOrDefault() in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 99
   at NzbDrone.Core.Organizer.NamingConfigService.GetConfig() in C:\projects\radarr-usby1\src\NzbDrone.Core\Organizer\NamingConfigService.cs:line 20
   at NzbDrone.Api.Config.NamingConfigModule.GetNamingConfig() in C:\projects\radarr-usby1\src\NzbDrone.Api\Config\NamingConfigModule.cs:line 51
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceSingle>b__38_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 147
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
Any Ideas?

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
https://github.com/Sonarr/Sonarr/commit/0553a39a02fd78a2926ef1d0e2acf9fc3f9bf25f

#### Issues Fixed or Closed by this PR
Fixes #2773

### CODE REVIEW

**Comment by Qstick** [comment]
Yea, only issue is knowing which one to delete. I suppose it doesn't matter though since this happens on first run and user is never able to change settings. I'll whip up a migration.

**Comment by galli-leo** [comment]
@Qstick Yeah, i would just delete the second one. Also do you know if your migration system cares about order? i.e. if you set this to be 148 and we merge it to nightly, but custom formats is 147, will that cause issues?

**Comment by Qstick** [comment]
Yea last I talked to @markus101  migrations system doesn’t care about order. If you look at Sonarr you see they have some placeholder numbers for future migration that’s in v3.

**Comment by Qstick** [comment]
@galli-leo seems there is already a housekeeper that takes care of this for us. https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupAdditionalNamingSpecs.cs

This error must occur if user hits settings prior to the housekeeper running.

**Comment by galli-leo** [comment]
Hmm, I think that wouldn't work if the browser is automatically open. So IMO we should add a migration regardless.

**Comment by Qstick** [comment]
Ok will do

**Pull request merged**
