### PR TITLE
#11 add Date Added to grid sort

### PR DESCRIPTION
**Pull request by wszeliga**
Add the ability to Sort Movies by Last/First Added

### CODE REVIEW

**Comment by onedr0p** [comment]
Any chance you can update his to use the Short Date options set in the UI settings?

image

**Comment by wszeliga** [comment]
Yes...as soon as I figure out where to get that information from, I'll get right on it.

**Comment by onedr0p** [comment]
Take a look at TimeleftCell.js

**Comment by wszeliga** [comment]
ok @onedr0p, I think I got it formatted.  Thanks for the pointer at TimeleftCell.js

**Comment by onedr0p** [comment]
Close, I think you just want the short date instead of '{date} at {time}'

**Comment by onedr0p** [comment]
Time isn't important to show.

**Comment by onedr0p** [comment]
You can see more examples below, also note show relative dates setting. That would be cool to be covered as well. Let me know if you have any questions.

https://github.com/Radarr/Radarr/search?utf8=✓&q=FormatHelpers

https://github.com/Radarr/Radarr/search?utf8=✓&q=shortdate

**Comment by onedr0p** [comment]
@wszeliga take a look how how I just did it for the in cinemas column on the movie page:

https://github.com/Radarr/Radarr/pull/946/commits/8c5045d6a0394593c5923e2f22f860ed3f181f13

**Comment by wszeliga** [comment]
Sorry got busy today and wanted to make sure I wasn't duplicating code.  Looks like there is already a RelativeDateCell "class", and I just used that instead.  Let me know your thoughts.

**Comment by onedr0p** [comment]
I added this in a PR, thanks!

**Pull request closed without merging**
