### PR TITLE
Use custom format languages for alternative titles

### PR DESCRIPTION
**Pull request by rubasace**
Take custom format languages into account when filtering out alternative titles and not only selected language

#### Database Migration
NO

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* #4284

### CODE REVIEW

**Comment by Qstick** [comment]
This is getting reworked a bit in https://github.com/Radarr/Radarr/pull/4058

**Comment by rubasace** [comment]
@Qstick I'm not sure I understand #4058 correctly. Will the translated titles be used when searching a movie on a tracker? What will then be used to decide the languages that get queried? The languages that we have configured on the indexer? Or the ones on the profile?

Also, does this mean that it's getting sorted as part of #4058 or just that this PR needs to be changed as the way we store the info changes?

**Comment by Qstick** [comment]
Either we need to fix in that PR or wait for that PR to merge as it touches same code areas and this is modifying things that will change in that PR

**Comment by rubasace** [comment]
@Qstick I can create a PR against the `aphrodite-language-improvements` branch if it's ok for you. The only question there is that I don't see `GetMovieInfo(int tmdbId, Profile profile, bool hasPreDBEntry)` anymore, just see `GetMovieInfo(int tmdbId, bool hasPreDBEntry)`but my fix certainly requires the Profile to be passed down. Is this something that can cause any other issue>

**Comment by rubasace** [comment]
@Qstick sorry to comment again. I've migrated my fix to the new branch but then realized during the writing of the unit tests that it isn't necessary as now we are storing all languages from the translations, which already seems to do the job. My question would be then, how will the languages be decided when querying the tracker? cause it seems like everything should be in place already

**Comment by Qstick** [comment]
On the new branch the tracker gets queried by the original name and the translation that is wanted in your profile. So we would still need to ensure any CFs that are wanted are added to the query list.

**Comment by Qstick** [comment]
Closing, we can talk in the other thread

**Pull request closed without merging**
