### PR TITLE
Added HDBits Category, Codec, and Medium Filtering Capability

### PR DESCRIPTION
**Pull request by randellhodges**
Added advanced configuration options to support filtering Categories, Codecs, and Medium to the HDBits indexer.

#### Database Migration
NO

#### Description
Adds support for hdbits category, codec, and medium api filter. The UI for these options is a little ugly and could be made prettier in the future once some sort of multiselect UI control is created. Instead of saving 17 different booleans and presenting the user with 17 different toggles, 3 comma delimited lists was used. Not the most end user friendly way, so it was hidden as an advanced configuration option.

The default behavior, if nothing is entered, is to work as it did before the change. Defaulting the categories might be a good thing to do in the future.

19ddffd0-2b5b-11e7-8c40-9602462dbfd6

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR
https://github.com/Radarr/Radarr/issues/1419

* #

### CODE REVIEW

**Comment by galli-leo** [comment]
I think we should add sensible defaults from the start (to not confuse users). Also, could you make them a tag input field (like preferred words)?

**Comment by randellhodges** [comment]
I'll take a look at the tags. I was concerned about controlling vocabulary. Like a person typed in movies, but the real word is movie, how annoying would it be to not know until you tried to save. I guess probably just as annoying as having to use a number...

**Comment by galli-leo** [comment]
Well I think you should just make the tag field for numbers not the words :)

**Comment by randellhodges** [comment]
I made some changes to support a controlled vocabulary. I adjusted the tag template to work in conjunction with the selectOptions attribute. If the selectOptions attribute is present, then the user will be presented tagging input that has a typeahead of the selectOptions.

**Comment by galli-leo** [comment]
That looks very cool! Can you move the code for type ahead to the already existing tag input (The one we use for Preferred words, must not contain, etc.)? That would be very cool!

**Comment by randellhodges** [comment]
I'll give it a try later today or tomorrow. The existing tag input for preferred words already had some stuff for matching (I think maybe it calls a web service for it) that might make it a bit difficult to implement without a lot of effort. Maybe not. I'll poke at it and see.

One thing about that, without a fair amount of effort, it would tie that tag input to the selectoptions. Maybe that isn't a big deal. Up to you guys.

**Comment by galli-leo** [comment]
Maybe make it conditionally. So it behaves like it currently behaves without selectoptions present?

**Comment by randellhodges** [comment]
Indeed, that is how I plan to tackle it.

**Comment by randellhodges** [comment]
The code has been moved into the TagInput include as is conditional based on the presence of the attribute tag-source.

**Comment by randellhodges** [comment]
@galli-leo Any issue with getting this merged?

**Comment by galli-leo** [comment]
Sorry I was caught up with finals in school and did not find the time to take a close look this :/ I should have time over the next few days.

**Comment by onedr0p** [comment]
@galli-leo if you need to test PM me on discord.

**Pull request merged**
