### PR TITLE
[wip] Slack/Mattermost notifications improvements from Sonarr

### PR DESCRIPTION
**Pull request by jamesmacwhite**
#### Database Migration
NO

#### Description

So looks like Sonarr implemented some improvements for Slack/Mattermost notifications in July. 

https://github.com/Sonarr/Sonarr/commit/e10717f6bb866baf545cc7071f34e276d4218321

I've ported these over to Radarr, however, I don't use Slack/Mattermost for notifications, therefore I'd want the original author of the linked issue to test/confirm if this fixes the issue or if further work is needed i.e. regressions.

Alternatively, I'll be willing to setup a test Slack channel or Mattermost server in a VM if no response from OP is forthcoming.

I will ping the original author in the issue

#### Issues Fixed or Closed by this PR

* #1769

### CODE REVIEW

**Comment by jamesmacwhite** [comment]
So testing the implementation, it appears to be working OK. A further fix from Sonarr was needed for image URLs not working. Here I did two tests one with the panda face emoji `:panda_face:` and the Radarr logo: (https://home-assistant.io/images/supported_brands/radarr.png)

radarr_slack_mattermost_emoji

radarr_slack_mattermost_image

If someone wants to test Mattermost, that would be great.

**Comment by galli-leo** [comment]
Gonna just merge these changes, and then the op of the issue can confirm if it fixed his issues.

**Comment by jamesmacwhite** [comment]
Sweet. Hopefully another issue ticked off for 0.2!

**Comment by seanvree** [comment]
@jamesmacwhite , @galli-leo  - I'm on develop Ver. 0.2.0.778  which branch do I need to be on to test?

**Comment by jamesmacwhite** [comment]
@seanvree Right now. Its currently on the nightly branch. It won't make it onto the usual pre-release develop branch until a new release is created. @galli-leo will pull that trigger on that whenever deemed appropriate.

Normally I wouldn't suggest this, but if you are comfortable with this sort of thing, you can temporarily switch to the nightly to get the new code changes from Sonarr for the Slack/Mattermost notifications. There was some recent shenanigans with DB issues, but this was temp resolved with the migration script which was causing problems, so the nighties are reasonably safe curerntly.

Backup your DB and install before hand though, I don't think a feature is worth borking your install, in the event of something happening.

Let me know.

**Comment by seanvree** [comment]
@jamesmacwhite  - Agreed, def not worth the bork. 

As I recall, after I back up the db. just change the branch to "nightly " in the webUI settings under General, correct?

**Comment by jamesmacwhite** [comment]
@seanvree Correct, then once set go to System > Updates then install latest. Usual update process will kick in to update you to the latest build from nightly.

Appreciate your willing to test this!

**Comment by galli-leo** [comment]
@seanvree To add to this: Radarr should do a backup before each update automatically, but better safe than sorry. (Db was actually never corrupted, but mapping logic was)

**Comment by seanvree** [comment]
Works!!!!

Thanks gents!

image

**Comment by jamesmacwhite** [comment]
@seanvree Woo! Go nuts with any icon image or emoji of your choice! `:panda_face:` strongly recommended!

**Pull request merged**
