### PR TITLE
Fixed: TMDB Failing due to missing response header

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
Seems our friends at tmdb have changed something, and the rate limit headers are not always returned. This will check for header in response instead of assuming it will be there

#### Issues Fixed or Closed by this PR

* #

### CODE REVIEW

**Comment by galli-leo** [comment]
Is there another header we could use to check? Or is it surely gonna be there when we need it?

**Comment by Qstick** [comment]
We can just set rate limit property for the httpRequest as that functionality is already built in and used for indexers. I am unsure if it shows up when needed or not as I didn't try loading it, it's still listed as an available auth header in the authHeaders header of the response but doesn't show up by default it seems. Could also be a temporary thing?

**Comment by galli-leo** [comment]
@Qstick If I understand the ratelimiting mechanic correctly, it basically only allows you to limit the request to one request per TimeSpan. I guess that would still work though, i think we should try doing that in addition to this update.

**Comment by Qstick** [comment]
Sounds good, should we set timespan to something like 0.5 sec? Given rate limit is 40 per 10 seconds, That gives us some buffer.

**Comment by Qstick** [comment]
Seems headers are back now, but I'll update this with the ratelimit as well so we are guarded in future if this happens again.

**Comment by Qstick** [comment]
@galli-leo looking at this a bit, not sure the built in rate limit will help given we are building a new HttpRequest for each Movie info call. Though I'm not familiar enough with the Http code to know.

**Pull request merged**
