### PR TITLE
Add support for additional Torznab indexer flags

### LINKED ISSUE #6268: Support Additional Indexer Flags for Torznab
Per discord discussions: Radarr only supports Freeleech flag from Torznab currently.

Changes need to be made on after a standard is decided on for passing indexer specific flags through Torznab

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* Fixes #6268

### CODE REVIEW

**Review by bakerboy448 — COMMENTED** [review]
Diff seems sane to me

**Review by Qstick — CHANGES_REQUESTED** [review]

**Comment by smh51** [comment]
hello, is this fix available ?

**Comment by smh51** [comment]
Doesn't seems to work,
image
PTP_GOLDEN or G_Freeleech or PTP_Approved are not applied when indexer is added via prowlarr. However, G_SCENE is working
image

I'm on docker version 5.0.3.8127

**Comment by ynnadanny** [comment]
Thanks, but that's about adding the ability to upgrade GP releases with newer ones when trumped.

This ticket is specifically about Radarr handling PTP's custom flags (PTP_Approved, PTP_Golden, etc.) **when using Prowlarr as an Indexer service**. Work was done to support flags in this scenario, but it looks like additional work is needed to support PTP flags.

**Pull request merged**
